### ISSUE TITLE
Add support for Matic testnet V3

### ISSUE THREAD

**Issue by Dizigen** [magiclabs/magic-js#102]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request
Feature request from Clash of Coins 
Currently only Matic testnet V2 is supported.

**Comment by harryEth** [comment]
Matic testnet V3 whitelisted. Closing this.
