### ISSUE TITLE
Support for Observables when sending and listening for chain events

### ISSUE THREAD

**Issue by Dizigen** [magiclabs/magic-js#103]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Clash of Coins would like to use a custom websocket(observables) endpoint to achieve higher performance when sending transactions and listening to chain events.

**Comment by smithki** [comment]
This request has not gained traction since it was originally opened. Will be closing this for now.
