### ISSUE TITLE
Support Expo SDK 38

### ISSUE THREAD

**Issue by Ethella** [magiclabs/magic-js#110]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Support Expo SDK 38
Bump peer dependency Webview version to 9.4

## 🧩 Context

To support the latest expo version

**Comment by smithki** [comment]
:rocket: Issue was released in [`@magic-sdk/provider@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%403.0.1), [`@magic-sdk/react-native@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%403.0.1), [`@magic-sdk/types@2.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%402.0.1), [`magic-sdk@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%403.0.1) :rocket:
