### ISSUE TITLE
Lock Magic associated sub-dependencies 

### ISSUE THREAD

**Issue by Ethella** [magiclabs/magic-js#129]
A potential issue

When developers lock an older version, for instance, "@magic-sdk/react-native@2.4.0"

Because we use `^` to lock the major version, the version of sub-dependencies will bump to @magic-sdk/provider@2.6.0.

To avoid introducing a potential issue to older versions during CI. We should lock the sub-dependencies in the package.json

**Comment by smithki** [comment]
I would be open to using `~` instead to get latest patch versions while locking minor versions!

**Comment by Ethella** [comment]
RN package dependencies have been updated via #132

**Comment by smithki** [comment]
Closing this for now as part of repository cleanup. We can re-open if the issue rises in priority.
