### ISSUE TITLE
[Magic SDK for React Native] Missing dependencies on Android build  

### ISSUE THREAD

**Issue by phbdias** [magiclabs/magic-js#131]
### ✅ Prerequisites

- [✅] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [✅] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I have been trying to integrate Magic SDK for React Native on a project, however I am struggling to get it to work properly.

When I build the app on an Android device, it fails with the following error: "Can't find variable: BigInt".
I managed to surpass this issue using a polyfill (i.e., inserting on global.js: global.BigInt = require('big-integer');).
However, another ReferenceError occurs ("Can't find variable: SharedArrayBuffer").
It is a configuration problem? 

Thanks in advance for any help you are able to provide! :)

### 🌎 Environment

| Software         | Version(s) |
| ---------------- : ---------- |
| "@magic-sdk/react-native": "^2.6.0" |
| "react": "16.13.1" |
| "react-native": "0.63.2" |
| "react-native-webview": "^10.8.2"  |
| `yarn`: 1.22.5  |
| Operating System : Android 10 |

**Comment by prbdias** [comment]
It might be related with the fact that React Native runs on top of JavaScriptCore which doesn't have support yet for BigInt nor SharedArrayBuffer. In theory and assuming this is the root cause, the library might work just fine on Chrome but have similar issue on Safari which also runs on top of JavaScriptCore. 
Would be interesting to understand which dependencies are using these unsupported native features.

**Comment by Ethella** [comment]
Hey @prbdias @phbdias, I'll take a closer look to see what's the missing pieces. Sorry for the late reply

**Comment by Ethella** [comment]
Here's an update to it. One of our RN dependency `whatwg-url` has recently updated their minor version with a change of major version update of `webidl-conversions`. In this package, it uses BigInt which RN env does not support at them moment. 

* whatwg-url@^8.1.0
  * webidl-conversions “^5.0.0”
* whatwg-url@^8.2.2
  * webidl-conversions@^6.1.0 (Use BigInt and Crashes)

I'll draft a quick fix to correct it. Thank you for your patience.

**Comment by Ethella** [comment]
`@magic-sdk/react-native@2.7.1` has been released to resolve the issue. Feel free to give it a try.

**Comment by prbdias** [comment]
> @prbdias @phbdias `@magic-sdk/react-native@2.7.1` has been released to resolve the issue. Feel free to give it a try.

@Ethella I've just tried and it's working like charm. 🎉🎉🎉

Thank you!

**Comment by smithki** [comment]
:rocket: Issue was released in [`@magic-sdk/provider@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%403.0.1), [`@magic-sdk/react-native@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%403.0.1), [`@magic-sdk/types@2.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%402.0.1), [`magic-sdk@3.0.1`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%403.0.1) :rocket:
