### ISSUE TITLE
[Magic SDK for React Native] Web3 calls not working due to undefined function

### ISSUE THREAD

**Issue by phbdias** [magiclabs/magic-js#139]
### ✅ Prerequisites

- [✅] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [✅] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

After the most recent changes on Magic SDK for React Native, I have been able to successfully login on Android. However, whenever I try to perform a web3 call, the following error occurs:

"TypeError: callbackify is not a function. (In 'callbackify(this.provider.request.bind(this.provider))', 'callbackify' is undefined)"

I tried with other providers and it works, so I guess the problem is related somehow with Magic, maybe something similar to the last issue I submitted here ([https://github.com/magiclabs/magic-js/issues/131](https://github.com/magiclabs/magic-js/issues/131)).

### 🌎 Environment

| Software : Version(s) |
| ---------------- : ---------- |
| @magic-sdk/react-native: 2.8.0 |
| react: 16.13.1 |
| react-native: 0.63.0 |
| react-native-webview: 8.0.0 |
| web3: 1.2.11 |
| yarn: 1.22.5 |
| Operating System : Android 10 |

**Comment by Ethella** [comment]
Sorry that I'm super busy with the IOS fix. I'll try to put some resources into the current week.

**Comment by phbdias** [comment]
It seems that the problem appeared when web3.js introduced the use of callbackify on version 1.2.10, however they are managing to surpass this problem on their new version ([](https://github.com/ethereum/web3.js/pull/3733)).

I am aware that Magic SDK is not supporting the recent versions (@1.3.x) of web3 and therefore, I won't be able to bump web3 to its last version, which solves this "callbackify issue". On the meantime, I downgraded web3.js to 1.2.9 to get the ethereum transactions working.

Thanks! :+1:
