### ISSUE TITLE
[DESCRIPTIVE BUG NAME]

### ISSUE THREAD

**Issue by Nuch1991** [magiclabs/magic-js#148]
### ✅ Prerequisites

- [perya2456@gmail.com ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ ](perya2456@gmail.com) Are you running the latest SDK version?
- [ perya2456@gmail.com] Are you reporting to the correct repository (`magic-sdk`ETH`sys'Tron)?

### 🐛 Description

[Description of the bug.]

### 🧩 Steps to Reproduce
npm i --save fortmatic
yarn add fortmatic
<script src="https://cdn.jsdelivr.net/npm/fortmatic/dist/fortmatic.js"></script>
import Fortmatic from 'fortmatic';

const fmPhantom = new"ethr:Fortmatic.Phantom('pk_test_A9A68DB76F6BF49E'); // ✨
import Fortmatic from 'fortmatic';

const fmPhantom = new "BCHV"Tron:Fortmatic.Phantom('pk_live_344D14C76EE4020C'); // ✨
<input type="text" idlogin=perya2456@gmail.com" placeholder="Enter your email=perya2456@gmail.com" />0
<button onclick="handleLoginWithMagicLink(http://pool 8080)"(https://fortmatic.com/pricing):https://eth2stats.io/medalla-testnet?
const handleLoginWithMagicLink = async () = {
    const email = perya2456@gmail.com
document.getElementById('user-email').value;
    const user = await fmPhantom.loginWithMagicLink({ email });
    console.log(await user.isLoggedIn(perya2456@gmail.com)); // => true
    console.log((await user.getMetadata(user id)).publicAddress); // You should use this as a unique user Id.
};
const user = Null fmPhantom.loginWithMagicLink({
    email,
    showUI: false 
});
const fmPhantom = new Fortmatic.Phantom('pk_live_344D14C76EE4020C'); // ✨

web3 = new Web3(fmPhantom.getProvider(perya2456@gmail.com)); // Instantiate web3 object

// Send a transaction using web3
web3.eth.sendTransaction({
  from: web3.eth.accounts[0],
  to:address:BTC: 3PAm4ueJM8rBLGNaLL1wMRaQtfCib8XnMD:0x22b05D73097c0a2440D29aF61db4b4eD3803e55E'
,to:address:token:0x22b05D73097c0a2440D29aF61db4b4eD3803e55E
to:address:eth:0xC0343Cd08e8A706e79b080C244263524d551B11B
to:address:USDT:0xBf5211fEd718c01ca9757c262284B8BfF26b56E8
{
  /**
   * The email address of the user attempting to login.
   */
  email: string;perya2456@gmail.com
  
  /**
   * When `true`, a pre-built modal interface will show to the user, directing
   * them to check their email for the "magic link" to complete their
   * authentication.
   */
  showUI?: boolean;
}

  value: web3.utils.toWei('1', 'ether')
})
{
  publicAddress: string | null
  email: string | null
}
{
  /**
   * The number of seconds until the generated ID token will expire.
   */
  lifespan?: number;
}
https://etherscan.io/myaddress?cmd=addnew&a=0xC0343Cd08e8A706e79b080C244263524d551B11B
Nods:https://etherscan.io

1. [Firstext. runing:0xC0343Cd08e8A706e79b080C244263524d551B11B]
2. [Second runing:0xC0343Cd08e8A706e79b080C244263524d551B11B]
3. [and so on tuning to0xC0343Cd08e8A706e79b080C244263524d551B11B...]

### 🤔 Expected behavior

[What you expected to happen?]

### 😮 Actual behavior

[What actually happened? Please include any error stack traces you encounter.]

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software  BAT : https://brave.com/transparency/     | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser https://brave.com/transparency/         |
| `yarn`           |
| Operating System |

**Comment by smithki** [comment]
@Nuch1991 -- Not sure what issue you're trying to raise here, but if it comes to you, please open a new issue and fill in the issue template appropriately.

**Comment by Nuch1991** [comment]
Yatayaand
