### ISSUE TITLE
Magic doesn't work in Vivaldi browser

### ISSUE THREAD

**Issue by mlejva** [magiclabs/magic-js#156]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

One of our users is using the [Vivaldi browser](https://vivaldi.com) and getting the following error `Magic RPC Error: [-32603] Internal error: Network Error`:

![Screenshot_from_2021-01-15_11-27-55](https://user-images.githubusercontent.com/5136688/104765543-57bb3000-5769-11eb-8ffd-709f88043905.png)

### 🤔 Expected behavior

Login should work.

### 😮 Actual behavior

Login doesn't work.

### 💻 Code Sample

```
...
const magic = new Magic(magicAPIKey);
...

(async function () {

    try {
      await magic.user.logout()
    } catch (error) {
      console.error(error);
    }

    const redirectURI = `${window.location.origin}/auth/redirect/${sessionID}`;

    try {
      await magic.auth.loginWithMagicLink({
        email,
        showUI: false,
        redirectURI,
      });
    } catch (error) {
      console.error(error);
    }
  })();
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 4.0.2
| Browser          | Vivaldi
| `yarn`           |
| Operating System | Ubuntu 20.04

**Comment by smithki** [comment]
I just tested the "happy" flow in Vivaldi with our [`"hello world"`](https://go.magic.link/hello-world) example and couldn't reproduce the issue.

The console error suggests a `Network Error` being raised from our `<iframe>`. Unfortunately this type of issue is oftentimes environmental (and temporary), though it would help to have some more information:

- Does the issue occur consistently in Vivaldi?
- Do other browsers work without the issue for this user?
- Does the user have any privacy-related browser extensions, VPNs, or device management profiles installed that could disrupt service to our APIs?

**Comment by mlejva** [comment]
After further investigation, it seems it was an issue on the user's side so this can be closed.

Sorry for the unnecessary issue. I'll investigate more thoroughly before I post here next time.
