### ISSUE TITLE
user.isLoggedIn returns true even if the user is not logged in

### ISSUE THREAD

**Issue by immortalObject** [magiclabs/magic-js#161]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When we're checking if a user is logged in on a brand new session (with cleared cookies or in incognito mode) using `isLoggedIn` function, magic for some reason tries to refresh session and eventually fails, but the function still returns true as if the user is logged in.

### 🧩 Steps to Reproduce

1. Run `user.isLoggedIn()`

### 🤔 Expected behavior

The function should return `false` if user is not logged in

### 😮 Actual behavior

The function returns `true`, but shows an error in the console: 
```
GET https://auth.magic.link/v1/session/refresh 400
```

### 💻 Code Sample

```JS
import { Magic } from 'magic-sdk'

const magic = new Magic(process.env.MAGIC_KEY)

// ...

const isLoggedIn = await magic.user.isLoggedIn() // isLoggedIn === true
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 4.1.1
| Browser          | Microsoft Edge v88.0.705.56
|                        | Chrome v88.0.4324.146
| `yarn`           | 1.22.5
| Operating System | Windows 10

**Comment by smithki** [comment]
Are you able to sign a new DID token in the scenario you describe? If `isLoggedIn` returns true, it indicates that the KMS session is active and the user should be able to sign a token. The `400` from `https://auth.magic.link/v1/session/refresh` is a red herring because we try to hydrate the session in a number of ways.

If you could provide a more detailed, reproducing example that would help us a lot in troubleshooting for you!

**Comment by immortalObject** [comment]
@smithki thank you for your response. There really isn't any additional info. It worked fine until today, but now, even in a completely blank session in incognito mode, it thinks I'm logged in. 

We call `isLoggedIn()` in the router to determine whether to redirect the user to the authentication page. The full code looks like this:

```JS
import { Magic } from 'magic-sdk'

const magic = new Magic(process.env.MAGIC_KEY)

// ...

router.beforeEach(async (to, from, next) => {
  const isLoggedIn = await magic.user.isLoggedIn()

  if (to.name == 'Home') {
    return isLoggedIn ? next({ path: '/dashboard' }) : next()
  }

  if (isLoggedIn) next()
  else next({ path: '/' })
})
```

I can't generate a new DID token since I'm not logged in. `magic.user.getIdToken()` just throws:
```
Magic RPC Error: [-32603] Internal error: User denied account access.
```

**Comment by smithki** [comment]
> @smithki thank you for your response. There really isn't any additional info. It worked fine until today, but now, even in a completely blank session in incognito mode, it thinks I'm logged in.
> 
> We call `isLoggedIn()` in the router to determine whether to redirect the user to the authentication page. The full code looks like this:
> 
> ```js
> import { Magic } from 'magic-sdk'
> 
> const magic = new Magic(process.env.MAGIC_KEY)
> 
> // ...
> 
> router.beforeEach(async (to, from, next) => {
>   const isLoggedIn = await magic.user.isLoggedIn()
> 
>   if (to.name == 'Home') {
>     return isLoggedIn ? next({ path: '/dashboard' }) : next()
>   }
> 
>   if (isLoggedIn) next()
>   else next({ path: '/' })
> })
> ```
> 
> I can't generate a new DID token since I'm not logged in. `magic.user.getIdToken()` just throws:
> 
> ```
> Magic RPC Error: [-32603] Internal error: User denied account access.
> ```

I've tried to reproduce this behavior with your code snippet (I'm assuming this is Vue router?), but was unable to. I'm wondering if there's a reproducing example available in a public repository I can try?

**Comment by immortalObject** [comment]
@smithki Everything started working a few days later, even though we hadn't changed anything on that branch. I talked to the team, and it turns out we've had the same problem a few times before. We tried clearing cookies/cache/browser data, use incognito mode, and even tested on other devices. In all cases we got the same thing: `isLoggedIn()` returns true even if the user is not logged in. The issue appears suddenly, without any related code changes, and then disappears the same way...

After some consideration, we decided to switch to auth0, so I'm closing the issue as it is no longer relevant

**Comment by osequi** [comment]
Today we've experienced the same problem.

On a fresh deployment, at the first attempt.
After a 2nd, 3rd etc attempts everything worked fine

**Comment by NullSoldier** [comment]
I'm reading this thread, and the developers haven't really explained in the SDK  the error occurs. Our user's are experiencing the same issue, when my machine doesn't experience it at all. Is it some magic link rate limiter? Can you just post an explanation for when this error can be thrown or is it a catch all that's send to the SDK? The above responder is not very technical, they are just saying they can't reproduce it on their machine. Can we get an engineer who knows the SDK to actually comment on the error itself and when you've programmed it to be thrown?

**Comment by Colhodm** [comment]
+1 to this issue...

**Comment by am-hernandez** [comment]
Hi @osequi @NullSoldier @Colhodm ,

#### If you are still experiencing an issue would you please open a new Issue on this repo? 

@NullSoldier , I am not sure what error message you are referring to. If it is `Magic RPC Error: [-32603] Internal error: User denied account access`, the error is thrown whenever you call a method that requires a logged in user. If I try to get the metadata of a user (`magic.user.getMetadata()`) but they aren't logged in then I will see that error.

**Comment by 0xatulpatil** [comment]
Hey, my app was just working fine till now, and for the past few days, I am too facing this error. What may be the issue here? 

![image](https://user-images.githubusercontent.com/67235572/235751536-dc89d6bf-2dd0-4638-ba03-ce551f1241dc.png)

**Comment by am-hernandez** [comment]
@0xatulpatil Would you please open a new issue for this? Thank you!

**Comment by am-hernandez** [comment]
@TomasGonzalez Would you please open a new issue for this? Thank you!

**Comment by 0xatulpatil** [comment]
Any updates regarding this?
