### ISSUE TITLE
[@magic-ext/oauth] Doing oauth.getRedirectResult() server side

### ISSUE THREAD

**Issue by PaulPCIO** [magiclabs/magic-js#162]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [ ] Are you reporting to the correct repository (`magic-sdk`)?

To start i'm not sure if this is the right repository but i notice a lot of the repos are directing to dead links on npm so it's hard finding the right place to report, eg;
- [@magiclabs/ui](https://www.npmjs.com/package/@magiclabs/ui)
- [@magic-ext/oauth](https://www.npmjs.com/package/@magic-ext/oauth)

this question is regarding `@magic-ext/oauth`

### ❓ Question

So currently i need to run the `oauth.getRedirectResult` function inside of a `useEffect`, as per [this example
](https://github.com/magiclabs/example-nextjs/blob/f027529e4dcb87bdc4ee076d9b686205fdf158d1/pages/callback.js#L28)

So i was wondering, if you use a framework like next.js with server side rendering. Would it be possible to get the results server side and handle the redirecting before the page render? example using [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering)

example:

```ts
export const getServerSideProps = (context) => {
  // all redirect queries are in context.req.query
  const authResult = magic.oauth.getRedirectServerResult(context.req)

  const authorised = await authenticateWithServer(authResult.magic.idToken)

  if(authorised){
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  
  return {
    props:{}
  }

}
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-ext/oauth`      | 0.7.0 | 
| Browser          | Chrome |
| `yarn`           |
| Operating System | Linux |
| next.js | 10.0.5 |

**Comment by smithki** [comment]
> To start i'm not sure if this is the right repository but i notice a lot of the repos are directing to dead links on npm so it's hard finding the right place to report, eg;

Sorry for the dead links, those repos are still private (not quite open-source ready yet... but someday).

Our key management design is self-sovereign. The user owns their identity. This necessitates that the `getRedirectResult` call happens client-side (via Magic's `<iframe>`). [You can read more about our approach to security here](https://docs.magic.link/security). While I won't say that a server-side approach is out of the question in the future, it comes with a number of unresolved technical and security questions. Self-sovereign key management is a difficult, though worthwhile problem to solve. With today's technology, there's a number of inconveniences to work around; though we are always looking to improve developer experience!

I'll close this issue as "resolved" for now, but feel free to ask questions and I'll answer them here for you.
