### ISSUE TITLE
How to handle or hide `POST https://api.magic.link/v2/auth/user/login/status 401` errors?

### ISSUE THREAD

**Issue by ValentaTomas** [magiclabs/magic-js#163]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

When we initialize the login flow with `loginWithMagicLink`, the browser dev tools console keeps printing `POST https://api.magic.link/v2/auth/user/login/status 401` errors:
![Screen Shot 2021-02-13 at 11 56 22](https://user-images.githubusercontent.com/49156497/107848415-963d1c80-6df3-11eb-83ba-be3998618a13.png)

How can we handle or suppress these errors, so that they won't show in the users' console? Normal error handling is not catching any errors.

Here is the code: 
![Screen Shot 2021-02-13 at 12 15 11](https://user-images.githubusercontent.com/49156497/107848621-27f95980-6df5-11eb-91a0-a8e3cc88f9b9.png)

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | CDN
| Browser          | Chrome
| `yarn`           |
| Operating System | macOS 11.1

**Comment by smithki** [comment]
It's understandable that these errors are a nuisance. Unfortunately, the browser decides to log these errors whether or not they are relevant (or properly caught). You can safely ignore these as they are related to the poller we use to check if the magic link has been clicked. We are planning to migrate to WebSockets or GraphQL subscriptions later this year.

**Comment by w3villa-anchal** [comment]
Hi, Is there any update on this? Is it possible to hide these errors from console if they have to be ultimately ignored?
