### ISSUE TITLE
How to do e2e tests using Cypress with Magic links?

### ISSUE THREAD

**Issue by jtoar** [magiclabs/magic-js#164]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I got started adding e2e tests for my application using Cypress. Cypress is [very opinionated](https://docs.cypress.io/guides/getting-started/testing-your-app.html#Logging-in) about how you test logging in. I.e., that you shouldn't just type and click through the UI to login, then run your test, but that you should make logging in a part of the test.

All well and good, except when it comes to Magic links&mdash;I have to open my email and click the link, which is the whole point and why we all love it! But I'm not sure how to test this in Cypress now. Do I just use the admin-sdk or something to get a token without ever entering my email in an input field? Just wondered what others were doing, if there was a golden path. Much appreciated!

Note that we're looking into this Cypress plugin for testing Magic's social login https://github.com/lirantal/cypress-social-logins, but still weren't sure how to test Magic's vanilla login.

**Comment by smithki** [comment]
For the near-term, I would recommend stubbing Magic methods with something like [`sinon`](https://sinonjs.org). The following snippet would work for a simple use-case:

```js
import sinon from 'sinon';
impor { Magic } from 'magic-sdk';

const magicInst = new Magic('FAKE_API_KEY');

myTestSuite.testCase('stubs magic', () => {
  const stub = sinon.stub(magicInst.auth, 'loginWithMagicLink');
  // ...
});
```

We are also actively working on built-in testing features to bypass the magic link flow or assert particular behaviors. I'll update this thread when those features are available!

**Comment by aglasserpfl** [comment]
@smithki 

Are any of those built-in testing features you mention above now available?

**Comment by smithki** [comment]
Yup! You can read about it [here](https://magic.link/docs/introduction/test-mode).

Bear in mind it does not support our server-side SDKs at this time; those will still need to be mocked to your specific case.
