### ISSUE TITLE
Can we get private key using magic js sdk

### ISSUE THREAD

**Issue by 3scava1i3r** [magiclabs/magic-js#167]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Actually I had to work on a dapp where a person would like to export their ethereum wallet how can i do that with Magic js sdk, can i at least get the private key?or mnemonic or even keystore?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser          |
| `yarn`           |
| Operating System |

**Comment by smithki** [comment]
Revealing the private key is a highly-sensitive user action and thus we do not allow integrating developers to access the private key. We have an ad-hoc system that we can deploy to allow users on a per-app basis get access to their key. Please get in touch with our support on the [Magic homepage](https://magic.link) (click the chat bubble at the bottom right) to see if this is a good option for your project.
