### ISSUE TITLE
violates the following Content Security Policy directive when i use a Web Socket "Custom Nodes" option

### ISSUE THREAD

**Issue by vincentlg** [magiclabs/magic-js#178]
### ✅ Prerequisites

const customNodeOptions = {
  rpcUrl: 'wss://rpc-mainnet.maticvigil.com/ws', 
  chainId: 137 
}

### 🐛 Description

Refused to connect to 'wss://rpc-mainnet.maticvigil.com/ws' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.magic.link/ https://*.fortmatic.com/ https://*.alchemyapi.io/ wss://*.ws.alchemyapi.io/ https://*.infura.io/ https://*.xdai.quiknode.pro ...

### 🧩 Steps to Reproduce

Subscribe to an event with the web3 magic provider configured as above.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  "magic-sdk": "^4.2.1"

The doc does not describe any restriction on WS RPC 
https://docs.magic.link/blockchains/ethereum#configure-custom-nodes

But it seems you need whitelists one or more of this "[official](https://docs.matic.network/docs/develop/network-details/network/)" web socket RPC provider 

wss://rpc-mainnet.maticvigil.com/ws or
wss://rpc-mainnet.matic.quiknode.pro or
wss://ws-matic-mainnet.chainstacklabs.com or
wss://matic-mainnet-full-ws.bwarelabs.com or
wss://matic-mainnet-archive-ws.bwarelabs.comor
wss://ws-mainnet.matic.network

Thank you

**Comment by smithki** [comment]
Our team will need to add this node to our CSP. Someone will ping this thread when it's complete.

**Comment by hcote** [comment]
@vincentlg Those URLs listed have been added

**Comment by smithki** [comment]
The CSP has been updated on our side. Please let us know if this is resolved by closing this issue 🙂

**Comment by vincentlg** [comment]
Thank you for your intervention, unfortunately I guess a problem persists on your side

`Access to XMLHttpRequest at 'wss://rpc-mainnet.maticvigil.com/ws' from origin 'https://auth.magic.link' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`

<img width="996" alt="Capture d’écran 2021-04-14 à 20 55 01" src="https://user-images.githubusercontent.com/813911/114764998-eb9a9900-9d64-11eb-8c78-fbdaa190c87a.png">

**Comment by smithki** [comment]
Looks like this new error is related to our CORS setup, will forward this to our infrastructure team and have them take a look.

**Comment by Genzan** [comment]
Good evening

I'm having the same problem when connecting to my custom node

const customNodeOptions = {
  rpcUrl: 'http://189.197.77.190:8545',
  chainId: 10
}

But having this error on console.

Content Security Policy: The page’s settings blocked the loading of a resource at http://189.197.77.190:8545/ (“connect-src”).

![imagen](https://user-images.githubusercontent.com/58860247/114792690-6e642980-9d4e-11eb-9411-78e764f36482.png)

**Comment by vincentlg** [comment]
> Looks like this new error is related to our CORS setup, will forward this to our infrastructure team and have them take a look.

👀 Any news from the infrastructure team ? :)

**Comment by smithki** [comment]
> 👀 Any news from the infrastructure team ? :)

Here's the current status: we don't have support for Web3 WebSocket subscriptions at this time. It's on our roadmap but I don't have an estimated release date for you.

**Comment by smithki** [comment]
> Good evening
> 
> I'm having the same problem when connecting to my custom node
> 
> const customNodeOptions = {
> rpcUrl: 'http://189.197.77.190:8545',
> chainId: 10
> }
> 
> But having this error on console.
> 
> Content Security Policy: The page’s settings blocked the loading of a resource at http://189.197.77.190:8545/ (“connect-src”).
> 
> ![imagen](https://user-images.githubusercontent.com/58860247/114792690-6e642980-9d4e-11eb-9411-78e764f36482.png)

@Genzan We allow `localhost` origins for testing custom node configurations. You can work around this by mapping that IP address to `localhost` in your `etc/hosts` file.

**Comment by Genzan** [comment]
> 
> 
> > Good evening
> > I'm having the same problem when connecting to my custom node
> > const customNodeOptions = {
> > rpcUrl: 'http://189.197.77.190:8545',
> > chainId: 10
> > }
> > But having this error on console.
> > Content Security Policy: The page’s settings blocked the loading of a resource at http://189.197.77.190:8545/ (“connect-src”).
> > ![imagen](https://user-images.githubusercontent.com/58860247/114792690-6e642980-9d4e-11eb-9411-78e764f36482.png)
> 
> @Genzan We allow `localhost` origins for testing custom node configurations. You can work around this by mapping that IP address to `localhost` in your `etc/hosts` file.

Im using the react example of yours as base to do these test (https://magic.link/posts/magic-react-express), also the ip 189.197.77.190 is a server diferent of my local computer. Will read about these host file as I have never work with one before, and tell you the results

**Comment by Genzan** [comment]
Already changed my Host file, but same problem persist

**Comment by smithki** [comment]
> Already changed my Host file, but same problem persist

You must also configure your Magic instance with a `localhost` origin given to the `network.rpcUrl` field. Unfortunately, that parameter cannot be an IP address as a matter of security.

**Comment by smithki** [comment]
@Genzan Please let me know if your concern has been resolved. If so, feel free to close the issue.

**Comment by Genzan** [comment]
We are currently working on getting a domain so I can pass to you, if you could give me a mail where I can summit it once it has been compleated I would be Happy to do so

**Comment by smithki** [comment]
@Genzan When your team is ready with a domain, go to https://magic.link and click the chat bubble at the bottom-right corner. You can communicate with our support team there!

<img width="1506" alt="Screen Shot 2021-04-28 at 9 59 45 AM" src="https://user-images.githubusercontent.com/22753882/116435498-a799a080-a808-11eb-9c53-149c5b0b9420.png">

**Comment by smithki** [comment]
Closing this for now! We're interested in exploring official WebSockets support in the future, but for now it's not an immediate priority.

**Comment by Genzan** [comment]
Hi already tried to talk via chat and email but they told me they were unable because of guidance of your security team

Any suggestions so we can advance in testing a Private Network Blockchain using MagicLink?

**Comment by smithki** [comment]
> Hi already tried to talk via chat and email but they told me they were unable because of guidance of your security team
> 
> Any suggestions so we can advance in testing a Private Network Blockchain using MagicLink?

At the time being, testing with a private chain infrastructure is not possible. However, we are looking at options internally that would remove this security requirement by emitting request to the node from our backend instead of client-side. Will keep you posted on the progress.
