### ISSUE TITLE
[react-native] Expo SDK 41 Support 

### ISSUE THREAD

**Issue by ajsmth** [magiclabs/magic-js#180]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

[Description of the bug.]

Looks like one of your dependencies (`localforage-asyncstorage-driver`) is using an old version of RNAsyncStorage. 
This module relies on file paths that are no longer supported in Expo 41 and so is crashing on launch

I've looked at the package and I'm not sure if its an internal one or not, but a migration to something with better support would be great! 

For context: 
<img width="1389" alt="Screen Shot 2021-04-22 at 2 02 31 PM" src="https://user-images.githubusercontent.com/40680668/115788556-9835d580-a378-11eb-978c-9e359eced907.png">

### 🧩 Steps to Reproduce

1. Get setup with the template repo for expo: `npx create-react-native-app --template with-magic`
2  Upgrade to Expo SDK 41 - `expo upgrade`
3. Start up application

**Comment by mirkokiefer** [comment]
Considered using React Native just to be able to use Magic after encountering this blocker for native iOS https://github.com/magiclabs/magic-ios-pod/issues/13 - any chance at least the React Native package can get updated soon to be usable?

**Comment by ajsmth** [comment]
just a note that RN should work fine, it's Expo that requires a fix. In either case, you can leverage `patch-package` and remove all `.expo` files in the module as a temporary workaround!

**Comment by smithki** [comment]
cc @Ethella

**Comment by mirkokiefer** [comment]
> just a note that RN should work fine, it's Expo that requires a fix. In either case, you can leverage `patch-package` and remove all `.expo` files in the module as a temporary workaround!

@ajsmth if updating the SDK is too complex, a branch with a temporary workaround would be great! Expo is the default starting point for RN projects, we can't justify going custom RN only for the auth lib to work. Ease of integration was our main hope for testing out Magic as an alternative to proven alternatives like Firebase or Auth0..

**Comment by Ethella** [comment]
> just a note that RN should work fine, it's Expo that requires a fix. In either case, you can leverage `patch-package` and remove all `.expo` files in the module as a temporary workaround!

I tried to do a fresh RN app with expo 41 and it works just fine. I'll do an update to the package and see if that resolves the issue.

**Comment by smithki** [comment]
:rocket: Issue was released in [`@magic-sdk/react-native@4.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native%404.3.1) :rocket:
