### ISSUE TITLE
Web browser already open or No matching activity - React Native Android Social Authentication

### ISSUE THREAD

**Issue by AsbarAli** [magiclabs/magic-js#184]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
       No open issues
- [x] Are you running the latest SDK version? 
       Yes
- [x] Are you reporting to the correct repository (`magic-sdk`)? 
       Yes

### 🐛 Description

My RN project is built with React Native CLI (Not expo) and I had to install unimodules to make support for the magic link library.
In iOS, all works fine but I got a weird error when I do the social authenticate in android.

### 🧩 Steps to Reproduce

When the user tries to do the social authenticate in RN android. 

### 🤔 Expected behavior

Social authentication popup should have appeared for the relevant domains (google, Facebook, etc.)

### 😮 Actual behavior

I am getting this error when I try to authenticate for the first time.
__
![alt text](https://drive.google.com/uc?export=view&id=1fY0agF9s2L8dO-d8hlEJ48AeXiUoR21g)

This error occurs when I try to attempt more than once.
__
![alt text](https://drive.google.com/uc?export=view&id=1OA_gu-Nzn8GoR3O01VWDgB3ePZpMSOTs)

### 💻 Code Sample

```
import {Magic} from '@magic-sdk/react-native';
import {OAuthExtension} from '@magic-ext/react-native-oauth';

const magic = new Magic('API_KEY', {
  extensions: [new OAuthExtension()],
});

await magic.oauth.loginWithPopup({
      provider: 'google',
      redirectURI: 'quantappfinance://quantapp` // Android Deep Linking URL
});
```
    
### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-sdk/react-native`      | 4.3.1
| `@magic-ext/react-native-oauth` | 0.3.0
| `React Native` | 0.64.0
| `Node version` | 12.19
| Browser          | RN Webview
| `yarn`           | 1.9.2
| Operating System | Android

**Comment by smithki** [comment]
cc @Ethella

**Comment by Ethella** [comment]
@AsbarAli Could you share your full package.json? 

We currently don't have full support for RN-CLI yet. I'll try to see if I can help

**Comment by AsbarAli** [comment]
hm but it worked in the previous app. (it is also implemented in RN CLI).  Please have a look at my package.json file and let me know if you see any solution here. 

```
{
  "name": "quantApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "storybook": "start-storybook -p 7007",
    "build-storybook": "build-storybook",
    "prestorybook": "rnstl",
    "format": "prettier --check ./src"
  },
  "dependencies": {
    "@magic-ext/react-native-oauth": "^0.3.0",
    "@magic-sdk/react-native": "^4.3.0",
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-clipboard/clipboard": "^1.7.0",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "@sentry/react-native": "^2.4.3",
    "bad-words": "^3.0.4",
    "d3-array": "^2.12.1",
    "d3-interpolate-path": "^2.2.1",
    "d3-scale": "^3.3.0",
    "d3-shape": "^2.1.0",
    "eslint-plugin-babel": "^5.3.1",
    "ethers": "^5.3.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-actions-sheet": "^0.4.8",
    "react-native-camera": "^3.43.9",
    "react-native-config": "^1.4.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-haptic": "^1.0.1",
    "react-native-haptic-feedback": "^1.11.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-permissions": "^3.0.4",
    "react-native-qrcode-scanner": "^1.5.4",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "^2.1.0",
    "react-native-redash": "^16.0.11",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-share": "^6.2.1",
    "react-native-shimmer-placeholder": "^2.0.7",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-switch-toggle": "^2.0.2",
    "react-native-touch-id": "^4.4.1",
    "react-native-unimodules": "^0.13.3",
    "react-native-vector-icons": "^8.1.0",
    "react-native-webview": "11.4.5",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3",
    "reduxsauce": "^1.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.13.16",
    "@babel/runtime": "^7.13.17",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-actions": "^5.3",
    "@storybook/addon-knobs": "^5.3",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.2",
    "eslint": "^7.25.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-react": "^7.23.2",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-dom": "17.0.1",
    "react-native-storybook-loader": "^2.0.4",
    "react-test-renderer": "17.0.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "@assets/icomoonConfig"
    ]
  },
  "config": {
    "react-native-storybook-loader": {
      "searchDir": [
        "./src"
      ],
      "pattern": "**/*.stories.js",
      "outputFile": "./storybook/storyLoader.js"
    }
  }
}

```

**Comment by pekq** [comment]
@AsbarAli were you able to find a workaround or solution to this problem?

I think https://github.com/expo/expo/issues/13937 & https://github.com/expo/expo/issues/12045 are related.
For now, we've targeted Android API 29 to avoid this. But as of Nov 1st, API 30 is forced by Google Play Store. Essentially blocking us from releasing binary updates.

**Comment by Ethella** [comment]
@pekq Taking a look into the issue

**Comment by Ethella** [comment]
It doesn't look like there's a solution right now. And other alternative packages are out-of-date. I'll chat with the team to see if it's possible to address a temporary solution to get around usage of `expo-web-browser`

**Comment by Ethella** [comment]
@pekq Do you mind upgrading `expo@44.0.5`  and manually add
```
    "@unimodules/core": "^7.1.2",
    "@unimodules/react-native-adapter": "^6.3.9",
```
and see if the error persists?

My Android simulator works after I upgrade to the latest versions. Please lmk if you find anything new.

**Comment by barakoles** [comment]
Any new on this? We are currently stuck and can't add social logins on react-native.

**Comment by Ethella** [comment]
> 

Could you share your package.json here? We are collecting more info related to this issue.

**Comment by barakoles** [comment]
> > Any new on this? We are currently stuck and can't add social logins on react-native.
> 
> @barakoles Could you share your package.json here? We are collecting more info related to this issue.

I can create another issue with more details if you want :)

**Comment by Ethella** [comment]
> > > Any new on this? We are currently stuck and can't add social logins on react-native.
> > 
> > 
> > @barakoles Could you share your package.json here? We are collecting more info related to this issue.
> 
> I can create another issue with more details if you want :)

If it's related to the `No matching activity` for RN Android social login, feel free to post it here. 😄

**Comment by barakoles** [comment]
@Ethella 
`package.json`:
```
{
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .ts,.tsx",
  },
  "dependencies": {
    "@bugsnag/react-native": "^7.14.1",
    "@datadog/mobile-react-native": "^1.0.0-rc2",
    "@datadog/mobile-react-native-navigation": "^1.0.0-rc2",
    "@magic-ext/react-native-oauth": "^0.4.0",
    "@magic-sdk/react-native": "^4.4.2",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@rematch/core": "^2.0.1",
    "@rematch/immer": "^2.0.1",
    "@rematch/loading": "^2.0.1",
    "@rematch/persist": "^2.0.1",
    "@rematch/select": "^3.0.1",
    "@rematch/updated": "^2.0.1",
    "@unimodules/core": "7.1.2",
    "@unimodules/react-native-adapter": "6.3.9",
    "axios": "^0.24.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "dayjs": "^1.10.3",
    "expo": "44.0.4",
    "expo-web-browser": "^10.1.0",
    "graphql": "^16.0.1",
    "graphql-request": "^3.6.1",
    "i18n-js": "^3.8.0",
    "immer": "^9.0.5",
    "lodash": "^4.17.20",
    "magic-sdk": "^4.4.2",
    "prettier": "^2.3.2",
    "react": "17.0.2",
    "react-hook-form": "^7.13.0",
    "react-native": "0.66.4",
    "react-native-animatable": "^1.3.3",
    "react-native-config": "^1.4.4",
    "react-native-dark-mode": "^0.2.2",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-resizer": "^1.4.5",
    "react-native-localize": "^2.1.4",
    "react-native-navigation": "^7.18.1",
    "react-native-reanimated": "2.2.4",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-textinput-effects": "^0.6.2",
    "react-native-webview": "^11.14.0",
    "react-query": "^3.28.0",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-logger": "^3.0.6",
    "validate.js": "^0.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@bugsnag/source-maps": "^2.3.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "@testing-library/jest-native": "^4.0.2",
    "@testing-library/react-native": "^8.0.0",
    "@types/enzyme": "^3.10.10",
    "@types/i18n-js": "^3.8.2",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.64.5",
    "@types/react-test-renderer": "^16.9.2",
    "@types/redux-logger": "^3.0.9",
    "babel-jest": "^26.6.3",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.27.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-react-native": "^3.11.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^7.0.4",
    "jest": "^26.6.3",
    "jest-enzyme": "^7.1.2",
    "lint-staged": "^11.2.6",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-dom": "^17.0.2",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2",
    "typescript": "4.1.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "prettier --write",
      "eslint --fix"
    ]
  },
  "expo": {
    "autolinking": {
      "exclude": [
        "expo-file-system"
      ]
    }
  }
}

```
So the steps I did were to:
1- Remove unimodules and magic
2- Add expo@44.0.4
2.1- I did some manual installation on `MainApplication.java` as automatic linking is not supported with `react-native-navigation`
3- Build successful
4- Add:  
-@unimodules/core@7.1.2
 -@unimodules/react-native-adapter@6.3.9
5- Build fails asking for `unimodules-app-loader`
6- Add: @unimodules-app-loader@3.0.0
7- Build fails with error:
```
AndroidManifest.xml:12:13-88 Error:
        Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules_react-native-adapter] AndroidManifest.xml:12:13-88
        is also present at [:expo-modules-core] AndroidManifest.xml:12:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:10:9-12:91 to override.
```

So apparently there's some conflicts with unimodules and expo. Maybe you guys will have to upgrade to expo as well instead of `react-native-unimodules`?

**Comment by RafSafeSocial** [comment]
The same here.

**Comment by Ethella** [comment]
Based on the thread, Installing a chrome browser to the emulator shall resolve the issue which it does on my emulator. https://github.com/expo/expo/issues/12045#issuecomment-1002067162 ​

Given that, in production, most Android users shall have a built-in chrome that is natively installed, in which case this shouldn't cause a production issue. And this is a defect in the `expo` package, therefore we plan to put our focus on other more important features at the moment but we will keep eyes on the issue and update our packages accordingly.

**Comment by jedahan** [comment]
The expo issue will be closed due to inactivity. It would be nice to comment there to maybe get the devs to give the issue a second look.
