### ISSUE TITLE
Algorand extension is missing a `signLogicSig(program)` method

### ISSUE THREAD

**Issue by solkimicreb** [magiclabs/magic-js#186]
### ✨ Feature Request

Could you add the `signLogicSig(program)` method to the Algorand extension? It is a feature that can not be polyfilled with `signTransaction` and it is provided by other signing wallets.

## 🧩 Context

`singLogicSig` or `lsig.sign` is used to [delegate signature authority](https://developer.algorand.org/docs/features/asc1/stateless/sdks/#account-delegation-sdk-usage) which is a core feature of the algorand blockchain.

## 💻 Examples

An equivalent functionality can be fund in the My Algo Wallet, which is a similar third party signing tool.

- Usage example: https://github.com/randlabs/myalgo-connect#sign-teal
- Implementation example: https://github.com/randlabs/myalgo-connect/blob/f42ca7e52aa24a5cd98c6300ee6e5df8c9fda48e/lib/main.js#L337

**Comment by smithki** [comment]
cc @harryEth

**Comment by solkimicreb** [comment]
Hi! Any update on this? I would be happy to help if you can point me in the right direction.

**Comment by ayv8er** [comment]
@solkimicreb Following up here and updating you. This feature request isn't one that's currently on our roadmap, but we will re-open the issue when it is.
