### ISSUE TITLE
Unable to get redirect result from social login

### ISSUE THREAD

**Issue by captain-melanie** [magiclabs/magic-js#187]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Hi, I'm trying to integrate social logins into our ReactJS frontend and following steps provided in your [sample code for social logins](https://codesandbox.io/s/sg212?file=/index.html) but they all fail at the last step `magic.oauth.getRedirectResult();`, although I have successfully logged in from the redirect popup. Do you have any idea what goes wrong? 

Login with email works perfectly, and connections for social logins have been tested in the Magic dashboard, so no issue with credentials.

Here's the error message from dev console
```
Error: Magic Extension Error (oauth): [invalid_request] State parameter mismatches.
    at new MagicExtensionError (sdk-exceptions.js?65bd:71)
    at OAuthExtension.BaseExtension.createError (base-extension.js?f3ca:110)
    at OAuthExtension.eval (index.js?a662:157)
    at step (index.js?a662:45)
    at Object.eval [as next] (index.js?a662:26)
    at fulfilled (index.js?a662:17)
```
Here's the error from network
```
Request URL: https://api.magic.link/v1/auth/user/redirect/login

data: {}
error_code: "AUTH_USER_MISSING_EMAIL_FOR_REDIRECT_LOGIN"
message: "Auth user is missing an email address for redirect login."
status: "failed"
```

Partial code
```
// this function is called upon clicking on the login button, which has no issue
export const requestSocialLogin = async magicLinkApi => {
    const didToken = await magicLinkApi.oauth.loginWithRedirect({
        provider: 'google',
        redirectURI: `${window.location.origin}`
    });
}
// this function is called in the callback context
export const completeSocialLogin = async magicLinkApi => {
    try {
        const result = await magicLinkApi.oauth.getRedirectResult();
        const profile = JSON.stringify(result.oauth.userInfo, undefined, 2);
        console.log(result);
    } catch (err) {
        console.log(err);
    }
}

```

// access to my local react app is possible, if that helps

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |4.3.0|
| `@magic-ext/oauth`      |0.8.0|
| Browser          |Chrome|
| `yarn`           |1.22.5|
| Operating System |Linux|

**Comment by captain-melanie** [comment]
Figured. 
window.location.search has been deconstructed somewhere before it gets to `getRedirectResult()`

```
    OAuthExtension.prototype.getRedirectResult = function () {
        var queryString = window.location.search;
        // Remove the query from the redirect callback as a precaution to prevent
        // malicious parties from parsing it before we have a chance to use it.
        var urlWithoutQuery = window.location.origin + window.location.pathname;
        window.history.replaceState(null, '', urlWithoutQuery);
        return getResult.call(this, queryString);
    };
```

Closing issue as Done.

**Comment by amankakar** [comment]
Hi @captain-melanie , I have also facing  the same issue, but not able to understand you solution. Can you please explain it in details.

**Comment by captain-melanie** [comment]
Hi @amankakar , it's been a long time, I vaguely remember that when I stepped into the code stack, the variable `window.location.search` has already gone before it got to `getRedirectResult`

**Comment by amankakar** [comment]
thanks @captain-melanie

**Comment by cbonaco1** [comment]
hey @captain-melanie  @amankakar I am facing the same issue as well but also not sure I follow the solution. yes it does seem the `getRedirectResult` function removes the query parameters from the URL and then sets that as the window.history state.

```javascript
const urlWithoutQuery = window.location.origin + window.location.pathname;
window.history.replaceState(null, '', urlWithoutQuery);
```

is that the `state` this error refers to? also are we saying that this error is expected? please let me know if you have any thoughts. thank you!
