### ISSUE TITLE
polkadot extension is missing sign utility

### ISSUE THREAD

**Issue by vikiival** [magiclabs/magic-js#188]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-SDK)?

### 🐛 Description

I would like to perform other transactions ([extrinsics](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.onfinality.io%2Fpublic-ws#/extrinsics)) with my Polkadot wallet.

However, according to the documentation, you can only perform send (`balances.transfer`) and contract interaction

### 🤔 Expected behavior

The Polkadot extension should have something like  `signTransaction` (#185)

**Comment by smithki** [comment]
cc @harryEth

**Comment by vikiival** [comment]
@harryEth @smithki any progress?

**Comment by harryEth** [comment]
@vikiival this is on our team's road map, but don't have a delivery day yet.

**Comment by vikiival** [comment]
🏓

**Comment by ayv8er** [comment]
We will re-open this issue when the feature request has a concrete timeline on our roadmap.
