### ISSUE TITLE
Mumbai RPC CORS block

### ISSUE THREAD

**Issue by mateus-batista** [magiclabs/magic-js#189]
### ✅ Prerequisites

- [X ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X ] Are you running the latest SDK version?
- [X ] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

`Access to XMLHttpRequest at 'https://rpc-mumbai.matic.today/' from origin 'https://auth.magic.link' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`Error: Magic RPC Error: [-32603] Internal error: Network Error
    at new MagicRPCError (sdk-exceptions.ts:32)
    at base-module.ts:42`

Most of my calls to contract methods throw the error above; the weird thing is that sometimes they work.

I'm using `web3.js`.

### 🧩 Steps to Reproduce

1. Create an instance of Magic
2. Create an instance of web3 with Magic as provider
3. Create an instance of a contract
4. Call a contract method

### 🤔 Expected behavior

Get the result from the contract call.

### 😮 Actual behavior

`Access to XMLHttpRequest at 'https://rpc-mumbai.matic.today/' from origin 'https://auth.magic.link' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`Error: Magic RPC Error: [-32603] Internal error: Network Error
    at new MagicRPCError (sdk-exceptions.ts:32)
    at base-module.ts:42`

### 💻 Code Sample

```
const customNodeOptions = {
  rpcUrl: https://rpc-mumbai.matic.today ,
  chainId: 80001,
}

const magic = new Magic(magicPublicKey, {
  network: customNodeOptions,
})

magic.network = "matic"

const web3 = new Web3(magic.rpcProvider)

const contract = new web3.eth.Contract(abi, contractAddress)

const balance = await contract.methods.balanceOf(address).call()

```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 4.3.0
| `web3`            | 1.3.5
| Browser          | Chrome Version 90.0.4430.212 (Official Build) (64-bit)
| `yarn`           | 1.22.5
| Operating System | Linux Mint 20 Cinnamon

**Comment by smithki** [comment]
cc @hcote

**Comment by hcote** [comment]
@mateus-batista The node URL `https://rpc-mumbai.matic.today` is allowed by our CSP, so you shouldn't be getting that error.

See this codesandbox example where I'm able to successfully connect to that Polygon URL - https://codesandbox.io/s/fragrant-frog-t7w2r?file=/index.html

You could also attempt to connect to either of these maticvigil Polygon URLs below if the one above continues to give you issues. 
https://rpc-mumbai.maticvigil.com (testnet)
https://rpc-mainnet.maticvigil.com (mainnet)

**Comment by mateus-batista** [comment]
Hey @hcote I wasn't able to create an instance of a `web3.eth.Contract` in your condesandbox (for some reason it freezes the app), but using the URLs you provided solved the problem, thanks very much.

**Comment by hcote** [comment]
@mateus-batista what's your contract wallet address on Polygon? See if plugging it into this codesandbox link below works (you'll also need the ABI). This is just a fork of the last codesandbox I shared with these code additions, and does allow me to grab the contract instance. 

Link: https://codesandbox.io/s/interesting-lumiere-qy404?file=/index.html
Code additions below

```
// Grab Contract
        const contractAddress = "0xfD827cC6d5b959287D7e1680dBA587ffE5dFcbB4";
        const abi = [
          {
            inputs: [],
            name: "message",
            outputs: [
              {
                internalType: "string",
                name: "",
                type: "string"
              }
            ],
            stateMutability: "view",
            type: "function"
          },
          {
            inputs: [
              {
                internalType: "string",
                name: "newMessage",
                type: "string"
              }
            ],
            name: "update",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function"
          }
        ];

        const contract = new web3.eth.Contract(abi, contractAddress);
        console.log(contract);
```

And for context, this is the smart contract code, even though it's not needed in this case to just grab an instance. 

```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

contract HelloWorld {
    string public message = "first message";

    function update(string memory newMessage) public {
        message = newMessage;
    }
}
```
