### ISSUE TITLE
Alchemy Polygon RPC `connect-src` Block

### ISSUE THREAD

**Issue by SweetmanTech** [magiclabs/magic-js#197]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Using the Polygon RPCs proviced by Alchemy are blocked with a `violatedDirective: "connect-src"` when attempting to initialize Magic.

### 🧩 Steps to Reproduce

1. Create customNodeOptions with `rpcUrl: https://polygon-mumbai.g.alchemy.com/v2/{API_KEY}` 🧞 
2. Create new instance of Magic (`const magic = new Magic(API_KEY, { network: customNodeOptions });`) 🐣 
3. Run your server `npm run dev`. 🏃 
4. Inspect your page (right click -> Inspect Page). 🖱️ 
5. Check the console logs, you should see the `SecurityPolicyViolationEvent` with `violatedDirective: "connect-src"`. 🔍 

### 🤔 Expected behavior

- I expect to be able to create a new instance of Magic with Alchemy's Polygon RPC_URL. 🧙 
- Magic accepts Alchemy's RPC format for Polygon: `https://*.g.alchemy.com/`.

### 😮 Actual behavior

Magic is expecting RPC URL format of: `https://*.alchemyapi.io/` 🔍 

However, Alchemy's Polygon RPC url is in this format: `https://polygon-mumbai.g.alchemy.com/v2/{API-KEY}` 🔗 

Causing Magic to throw an error, despite receiving a valid RPC URL. 🚨 

```
import { Magic } from 'magic-sdk';
import { ethers } from 'ethers';

const customNodeOptions = {
	rpcUrl: "https://polygon-mumbai.g.alchemy.com/v2/{ALCHEMY_API_KEY}",
	chainId: process.env.CHAIN_ID,
	network: process.env.NATIVE_CURRENCY_NAME,
}

export const magicMatic = new Magic(MAGIC_API_KEY,
	{ network: customNodeOptions }));

export const provider = new ethers.providers.Web3Provider(magicMatic.rpcProvider));
```

running the code with `npm run dev` (NextJS) opens a browser. 🧑‍💻 

When you inspect page, this error appears: 🔍 

<img width="993" alt="Screen Shot 2021-08-30 at 5 23 44 PM" src="https://user-images.githubusercontent.com/23249402/131325496-4b279ef8-70bd-41cb-a6c0-415fef912cb2.png">

### 💻 Code Sample

```
import { Magic } from 'magic-sdk';
import { ethers } from 'ethers';

const customNodeOptions = {
	rpcUrl: "https://polygon-mumbai.g.alchemy.com/v2/{ALCHEMY_API_KEY}",
	chainId: process.env.CHAIN_ID,
	network: process.env.NATIVE_CURRENCY_NAME,
}

export const magicMatic = new Magic(MAGIC_API_KEY,
	{ network: customNodeOptions }));

export const provider = new ethers.providers.Web3Provider(magicMatic.rpcProvider));
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | `^4.4.1`
| Browser          | `Brave`
| `yarn`           | `1.22.11`
| Operating System | `Mac OS Big Sur 11.5.2`

**Comment by smithki** [comment]
Please contact our support team [here](https://magic.link) so we can discuss adding your custom node provider to our CSP.

![Uploading Screen Shot 2021-08-30 at 1.22.33 PM.png…]()
