### ISSUE TITLE
No available storage method found in React Native

### ISSUE THREAD

**Issue by holmanlam** [magiclabs/magic-js#204]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Hello, I want to implement magic link in React Native App, but two error codes appeared when I called "magic.auth.loginWithMagicLink". Do you know how to solve it. Many Thanks

Here is my sample code:

![image](https://user-images.githubusercontent.com/26771956/132169488-30864ee4-d2ce-416a-8f1c-073fe83a6fc1.png)

Two error will appeared
![image](https://user-images.githubusercontent.com/26771956/132169546-9c98a6e2-f2ac-4d46-bf4c-275b0576f7fd.png)

![image](https://user-images.githubusercontent.com/26771956/132169557-088ee9ad-b9ee-4818-b347-3edcd8881f84.png)

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-sdk/react-native`      | `^5.1.0`
| Browser          | React Native (iOS)
| `yarn`           | `1.22.10`
| Operating System | `iPhone 12`

**Comment by Ethella** [comment]
@holmanlam Hi. Could you move 'magic.Relayer' to a parent component like 'app.js' as it's relayer that doesn't need to be re-rendered?
