### ISSUE TITLE
Magic-js prevents the use of Polygon nodes provided by Alchemy.com for security reasons

### ISSUE THREAD

**Issue by david03g** [magiclabs/magic-js#222]

**Comment by smithki** [comment]
Our support team can most likely get this sorted for you. Please follow the steps provided in our [documentation](https://magic.link/docs/introduction/faq#why-is-my-custom-node-configuration-not-working-due-to-csp-errors).

Also, as a general open-source tip, it helps to add as much context to your GitHub issue as possible. Thankfully, I have a good feeling that I know what you are asking for here, but just as easily someone else might not understand the underlying problem.
