### ISSUE TITLE
Add Aurora RPC endpoints

### ISSUE THREAD

**Issue by mightymatth** [magiclabs/magic-js#238]
### ✨ Feature Request

Add RPC endpoints for Aurora from [the official documentation](https://doc.aurora.dev/develop/networks).

Additionally, Aurora will support RPCs with API keys in the following format:
```
https://mainnet.aurora.dev/<API-KEY>
```
...so it will be nice to handle this case in your whitelist regex expressions.

## 🧩 Context

Related to #178

**Comment by smithki** [comment]
You can follow [steps in our docs](https://magic.link/docs/introduction/faq#why-is-my-custom-node-configuration-not-working-due-to-csp-errors) to request your custom Node provider is added to our CSP whitelist.
