### ISSUE TITLE
Algorand Extension is missing signMultisigTransaction

### ISSUE THREAD

**Issue by Standaa** [magiclabs/magic-js#241]
### ✅ Prerequisites

• ✅ Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
• [ ] Are you reporting to the correct repository (`magic-sdk`)?
> No, proper repo is closed-source

### ✨ Feature Request
The current Algorand extension is missing Algorand's sdk `signMultisigTransaction` method.
Makes it impossible to use Magic for  multisig transaction signing (this is not the only method required, `appendSignMultisigTransaction` is another).
@harryEth I saw you worked on the Algorand extension. Would be happy to help build this feature if the code can be open sourced.

## 🧩 Context
I am trying to build a flow, whereby a quorum of users can agree on locking up a bounty in an escrow.

## 💻 Examples
MyAlgoWallet has this built natively.

**Comment by Standaa** [comment]
#https://github.com/magiclabs/magic-js/issues/186

**Comment by Standaa** [comment]
Somewhat related to [#186](https://github.com/magiclabs/magic-js/issues/186)

**Comment by smithki** [comment]
cc @harryEth

**Comment by ayv8er** [comment]
@Standaa Thank you for the feature request. I wanted to follow up on this and let you know, that although we don't have this request on the roadmap, we will re-open the issue when it is.
