### ISSUE TITLE
Add preload option to Magic constructor to prevent preloading css when using a custom UI

### ISSUE THREAD

**Issue by W4G1** [magiclabs/magic-js#243]
### ✅ Prerequisites

- [ x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Add a `preload` option to the Magic constructor to optionally preload UI assets. Currently when you don't want to use the default UI, you can use `showUI: false` on `loginWithMagicLink()`, but the UI has already been preloaded before that function can be called.

## 🧩 Context

Evidence of magic instance preloading UI assets when constructed:

![image](https://user-images.githubusercontent.com/38042257/141162275-0f976dfd-6935-4e1e-891b-3df7b179cc0f.png)

## 💻 Examples

My proposal is something like this to prevent preloading UI assets:

```javascript
new Magic('pk_live_something', {
  preload: false // To prevent preloading default UI
});
```

**Comment by vertti** [comment]
NextJS example app for Magic prints a lot more preload warnings on every page load:

<img width="648" alt="Screenshot 2022-04-14 at 10 30 01" src="https://user-images.githubusercontent.com/557751/163357198-b29d2d34-f9df-4903-984d-0e14e24bb0cc.png">

**Comment by am-hernandez** [comment]
Thank you @W4G1 for the feature request. I have added this to our feature request log so that our team can discuss adding this feature to the roadmap.
