### ISSUE TITLE
Force google account chooser

### ISSUE THREAD

**Issue by mlnchk** [magiclabs/magic-js#247]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Now, if my browser knows only one google account, Magic login flow skips Google account chooser and logs me into the only account available. But sometimes I need an opportunity to use chooser because there is a "Use another account" button on this page.

![CleanShot 2021-12-05 at 16 11 03@2x](https://user-images.githubusercontent.com/25712010/144747934-8ee93f0e-e650-404f-ac34-ca003907f81f.png)

## 🧩 Context

The change is pretty simple, it is just one URI parameter at the same level that `scope` — `prompt`. You can see docs [here](https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters).

## 💻 Examples

I think, it should look something like this:

```js
magic.oauth.loginWithRedirect({
    provider: 'google',
    redirectURI: `${BASE_URL}/auth/success/oauth`,
    prompt: 'select_account',
  })
```

**Comment by am-hernandez** [comment]
Hi @mlnchk ,

We have evaluated this feature request and have not made plans to add it to our roadmap at this time. We are open to reconsidering the feature if we see a wider need for it in the future.

Thank you for posting this feature request!

**Comment by rhyek** [comment]
I'm implementing social login with google and just stumbled upon this. I think the exact api proposed above should work. More info here:

https://developers.google.com/identity/protocols/oauth2/web-server#:~:text=user%20for%20consent.-,select_account,-Prompt%20the%20user
