### ISSUE TITLE
Missing Authorization Header

### ISSUE THREAD

**Issue by melissafzhang** [magiclabs/magic-js#258]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I'm seeing intermittent errors when using `loginWithCredential` using magic-sdk.

### 🧩 Steps to Reproduce
Unfortunately I'm not able to reproduce since it happens most often on mobile web and intermittently. 

### 🤔 Expected behavior
Expect error not to throw

### 😮 Actual behavior

![image](https://user-images.githubusercontent.com/38673112/147509205-cd4ce395-3ff9-4755-a950-5c34a43897d4.png)

### 💻 Code Sample

```
let magic: Magic | undefined;
if (
  typeof window !== "undefined" &&
  process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY
) {
  magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY);
}

export const useLoginCallback = (): string => {
  const [login] = useMutation(LOGIN);
  const [error, setError] = useState("");
  useEffect(() => {
    async function completeLogin() {
      if (!magic) return;
      if (typeof window === "undefined") return;
      try {
        const didToken = await magic.auth.loginWithCredential();
        const { data } = await login({
          variables: { didToken },
        });
      } catch (e) {
        setError(e.message);
      }
    }
    completeLogin();
  }, []);
  return error;
};
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 7
| Browser          | Chrome Mobile, Safari Mobile
| `yarn`           | 1.22.4
| Operating System | Mac OSX

**Comment by smithki** [comment]
Please take the time to share a CodeSandbox which demonstrates the issue. The code snippet you provided is much appreciated, but it only encapsulates the "callback" side of the login flow. We'll need to see a complete implementation to understand if there's a bug.

**Comment by melissafzhang** [comment]
@smithki the issue is intermittent on mobile web so I haven't been able to reproduce. We are calling the function on the callback url page if that helps.

**Comment by smithki** [comment]
The issue, as described, potentially indicates the callback query parameter might be missing or malformed by the time `loginWithCredential` is called. Without a more complete implementation or reproduction, though, there's not enough information for us to deduce what's affecting your particular case.

**Comment by melissafzhang** [comment]
Oh interesting, the error seems to suggest that there's a missing http header. I'll add some more logging and see if I can get the query params that are present when the error happens.

**Comment by melissafzhang** [comment]
I logged the query params, and it appears that there are no query params present when the function is called. Any idea as why that would be happening?

**Comment by smithki** [comment]
Unfortunately, without a full code sample (even one that reproduces the issue only occasionally), I can't discern that for you 😞

**Comment by am-hernandez** [comment]
Hi @melissafzhang , I've been reviewing your case.  Unfortunately I'm unable to reproduce the problem so will be marking it closed.  If you're still experiencing issues, feel free to reply back with more details and/or a reproducible code snippet and we can revisit.  Thanks!
