### ISSUE TITLE
Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by royalvirendra** [magiclabs/magic-js#259]
### ✅ Prerequisites![Screenshot 2021-12-29 at 12 28 04 PM](https://user-images.githubusercontent.com/75446531/147635607-6e8cf0ce-ad67-4c6d-abad-4a5f26f15b29.png)
- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ question
Frame Work react-native
- Build fail in xcode 13 due to Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator.

Added IN Podfile:
           
         pod 'MagicSDK'
         pod 'BigInt'
  
also tried to add 'x86_64-apple-ios-simulator'/ 'arm64'/ 'arm64-apple-ios-simulator' in EXCLUDED_ARCHS in Build Settings.

and also i have imported  lib in build phases shown in [image](https://user-images.githubusercontent.com/75446531/147635678-cc9a5a11-fd68-42b8-9852-342ec2004f62.png): 
  
  
  
  
              
  
### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |2.4.0           |
| `BigInt`              | 5.2.0            |
| Browser          |
| `yarn`           |
| mac os|

**Comment by Yara1990** [comment]
Thank you @Ethella for taking this up. Please let me know if you need any further details.

**Comment by Ethella** [comment]
@royalvirendra @Yara1990 

Just to clarify, do you use a pure CRNA framework without Expo? And do you link `MagicSDK.xcframework` for iOS after RN iOS build?

**Comment by royalvirendra** [comment]
yes we use a pure CRNA framework without Expo And we already link MagicSDK.xcframework for iOS.

**Comment by royalvirendra** [comment]
steps i have done :

step1:  installed package "@magic-sdk/react-native" 

- follow steps as per given in package.
- work in android.

step2: For IOS:

1. Added  pod 'MagicSDK' in pod file.  && link MagicSDK.xcframework in link binary with libraries.
2. Getting Error: 

### MagicSDK-Web3 Group
   **Swift Compiler Error Group**
               ios/Pods/MagicSDK-Web3/MagicSDK-Web3/Classes/ContractABI/ABI/ABI.swift:9:8: Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Build/Products/Debug-iphonesimulator/BigInt/BigInt.swiftmodule

   **Swift Compiler Warning Group**
            /Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MagicSDK-Web3.build/Objects-normal/x86_64/ABIConvertible.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature")
Uncategorized Group

**Command CompileSwift failed with a nonzero exit code** 

3. Added pod 'BigInt' 

![Screenshot 2022-01-08 at 3 48 47 PM](https://user-images.githubusercontent.com/75446531/148640612-a37fee1c-f1f6-4e40-b8c5-94d06a91be5b.png)
 
Even after adding Bigint pod, the error does not get resolved.
   
4. Also try build active architectures only set as (true). And in Exclude architectures i have try to add ( 'x86_64-apple-ios-simulator',  arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7)

 Even after adding Bigint pod, the error does not get resolved.

![image](https://user-images.githubusercontent.com/75446531/148640452-87abc320-7d45-47a4-8cd3-9d31577a23a2.png)

**Comment by Ethella** [comment]
@royalvirendra Just FYI, this setup is not officially supported by Magic yet. We recommend you to use Expo managed flow or Native iOS / Android. However, I'm glad to take a look and see if I can help.

**Comment by royalvirendra** [comment]
**@Ethella** I have tried Magic link integration with native IOS using following link.

[Magic for iOS Apps](https://magic.link/docs/login-methods/email/integration/ios).

As per given above link we have applied following steps.

1. Add pod 'MagicSDK' IN podfile.
2. run command pod install and after that we get successfully completed Pod installation.
3. After completion of Pod installation. i have Created swift file and SDK Instance.
4. and tried to build project.

After Build project, i'm getting some issue which is given below.

### Swift Compiler Error Group
        ios/Pods/MagicSDK-Web3/MagicSDK-Web3/Classes/ContractABI/ABI/ABI.swift:9:8: Could not find module 'BigInt' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: Library/Developer/Xcode/DerivedData/goqcixtxpjcuiwhhzuvlolqekwxh/Build/Products/Debug-iphonesimulator/BigInt/BigInt.swiftmodule
### Swift Compiler Warning Group
      Library/Developer/Xcode/DerivedData/-goqcixtxpjcuiwhhzuvlolqekwxh/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/MagicSDK-Web3.build/Objects-normal/x86_64/ABIConvertible.dia:1:1: Could not read serialized diagnostics file: error("Invalid diagnostics signature")
### Uncategorized Group
  Command CompileSwift failed with a nonzero exit code.
### Swift Compiler Error Group
    ios/Magic.swift:10:8: Failed to build module 'MagicSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)'). Please select a toolchain which matches the SDK.
      /Volumes/Data-Storage/devgithub/VersoViewMobileApp/ios/Magic.swift:22:5: Expected declaration
      /Volumes/Data-Storage/devgithub/VersoViewMobileApp/ios/Magic.swift:13:7: In declaration of 'AppDelegate'
      
podfile:
![Screenshot 2022-01-10 at 12 19 19 PM](https://user-images.githubusercontent.com/75446531/148727519-b4df335f-a302-4d03-bc51-f725d4ec25a4.png)


Some snap shot's:
         ![Screenshot 2022-01-10 at 11 30 47 AM](https://user-images.githubusercontent.com/75446531/148725505-9e182640-f703-40de-9943-9a1f644881dc.png)
      
     
![Screenshot 2022-01-10 at 11 28 52 AM](https://user-images.githubusercontent.com/75446531/148726030-2317e517-3055-4032-9d21-f4054cedbf8d.png)

**Comment by Ethella** [comment]
For Compiler Error, could you check if `BUILD_LIBRARY_FOR_DISTRIBUTION = YES` is properly set in the build settings

![image](https://user-images.githubusercontent.com/33166884/148881856-67a4d277-b3c4-4d08-aace-8094b2defc2c.png)

---
For the `BigInt` error, the library is imported via source code, therefore it shouldn't bring any problem when compiling for target `x86_64_simulator`. And MagicSDK.xcframework has included this target already.

![image](https://user-images.githubusercontent.com/33166884/148882475-32101d6d-6c6f-41fe-9f4b-47c0cbef5b75.png)

I would recommend you to do a project clean first and see if `BigInt` still brings problem

**Comment by royalvirendra** [comment]
We changed BUILD_LIBRARY_FOR_DISTRIBUTION = YES. Also we cleaned the project and tried to build it again, but still we are facing the same problem with "BigInt".

![Screenshot 2022-01-11 at 11 44 35 AM](https://user-images.githubusercontent.com/75446531/148891760-184ab4c7-433e-424e-bdfc-07bcfac0ff76.png)

**Comment by Ethella** [comment]
It's a bit odd since the package `BigInt` is installed in source code, not as a binary file. So there would be hardly an unsupporting simulator issue.

Do you mind inviting me to the project so I can take a closer look?

**Comment by AlphatechUSA** [comment]
Hi Ethella, you should now have read access to our project.

**Comment by Yara1990** [comment]
@Ethella Did you get a chance to look at the codebase? It would be great if we can have an ETA for this issue?

**Comment by Ethella** [comment]
@Yara1990 I had checked the codebase and I don't think I can offer you a quick fix at the moment. 

However, I would suggest you wait for a bit more till our ios package `MagicSDK` gets open-sourced this week and released on SPM. It might help you to resolve the missing module for an x86 target as the project won't be using xcframework but the source code instead.

**Comment by Ethella** [comment]
Closing this for now. Feel free to reopen this issue or start a new one when you encounter any issue during the development of our new SPM / Cocoapod / open-source package.
