### ISSUE TITLE
Not Exporting package.json in @magic-ext/solana

### ISSUE THREAD

**Issue by bmeeder22** [magiclabs/magic-js#272]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When using `@magic-ext/solana` a warning is appearing while trying to startup the app. 

```
warn Package @magic-ext/solana has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in node_modules/@magic-ext/solana/package.json
```

### 🧩 Steps to Reproduce

1. Create a React Native 
2. Run `yarn android`
3. See the warning in the logs

### 🤔 Expected behavior

We don't see the warning

### 😮 Actual behavior

We see the warning

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-sdk/react-native`      | 7.0.0
| `@magic-ext/solana` | 3.0.1
| Browser          | `react native`
| `yarn`           | `1.22.17`
| Operating System | `android Q`

**Comment by bmeeder22** [comment]
Some more context on how this is a best practice: https://github.com/uuidjs/uuid/issues/444#issuecomment-630424195

**Comment by smithki** [comment]
I took a gander at the PR (#273) and found a few issues that would block this change in the short-term. [More context here](https://github.com/magiclabs/magic-js/pull/273#issuecomment-1022450802).

I'm going to close this as `wontfix` for now, but happy to keep the discussion rolling in this issue or in the PR.

**Comment by bmeeder22** [comment]
Sounds good thanks for the help!
