### ISSUE TITLE
Random errors Magic RPC Error [-32603] and Failed to retrieve OAuth access token

### ISSUE THREAD

**Issue by mpetricek** [magiclabs/magic-js#277]
EDIT: After testing newest version, the first problem is still present. Happening if firstly logging in with social login and after that with email magic link (but not every time). I'll test it more to see if the second problem is present too.

### ✅ Prerequisites

- [ yes] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [yes ] Are you running the latest SDK version?
- [ yes] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I'm getting randomly these two errors. We are using it together with NextJS.

Magic RPC Error [-32603] usually happens on callback from opened email magic link.
![Screenshot 2022-01-28 232317](https://user-images.githubusercontent.com/15015171/151634125-5845fe2e-faeb-4f00-8ece-661494e1218e.png)

OAuth access token happens on callback from social login. Google to be exact.
![Screenshot 2022-01-29 000454](https://user-images.githubusercontent.com/15015171/151634173-6433ecee-a5a5-418a-a29b-2ae5b4e0e237.png)

They are not appearing regulary but randomly. In dev enviroment it usually helped to remove all MagicJS cookies.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.0.1
| Browser          | Firefox 96 / Chrome 97
| `npm`           | 6.14.14
| Operating System | Windows 11

**Comment by mpetricek** [comment]
EDIT: Both errors still prezent in newest version. Any update on this?

**Comment by jackie-nguyen** [comment]
I'm also having this issue. Sign in with Oauth (Google in this case) will only work randomly.

```
Magic Extension Error (oauth): [server_error] Failed to retrieve OAuth access token.
```

When it does work, I get this error
```
TypeError: Cannot destructure property 'verifier' of 'JSON.parse(...)' as it is null.
```

I am using this function call
```
      const res = await magic.oauth.getRedirectResult().catch((err) => {
        console.log("the error is here: ", err);
      });
```

**Comment by AJax2012** [comment]
@mpetricek I just want to check to make sure I understand what the issue you're facing is - Are you trying to log into your app with Google OAuth, but through an email link? Is that where you're seeing errors?

**Comment by mpetricek** [comment]
@AJax2012 No, there are two errors. -32603 is happening when using magic link flow (link in email). Failed to retrieve oauth access token happens when using Google oAuth.

**Comment by AJax2012** [comment]
@mpetricek do you have examples of any of your code? It would be difficult to recreate or debug without any samples.

**Comment by smithki** [comment]
To aid in our troubleshooting, please provide a reproducible example of the problem.

**Comment by am-hernandez** [comment]
While reviewing this case I've been unable to reproduce the problem so will be marking it closed.  If you're still experiencing issues, feel free to reply back with more details and/or a reproducible code snippet and we can revisit.  Thanks!
