### ISSUE TITLE
Internal error: Expected Buffer still happening for Solana TX's on @magic-sdk/react-native 8.1.0

### ISSUE THREAD

**Issue by bmeeder22** [magiclabs/magic-js#278]
I am testing this fix using the demo application which can be found here: https://github.com/bmeeder22/solana_magic_demo. Even after pulling in `"@magic-sdk/react-native": "8.1.0"` and `"@magic-ext/solana": "4.0.1"` I am still getting the same error message as before.

_Originally posted by @bmeeder22 in https://github.com/magiclabs/magic-js/issues/269#issuecomment-1026208496_

**Comment by bmeeder22** [comment]
@Ethella

**Comment by Ethella** [comment]
There's an internal change getting deployed at the moment. Please wait for a moment.

**Comment by Ethella** [comment]
@bmeeder22 It's been deployed. Changes are live!
