### ISSUE TITLE
High CPU load while logging in with email

### ISSUE THREAD

**Issue by guillaumervls** [magiclabs/magic-js#280]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

While I log in with the default UI with the following line:
```js
const token = await magic.auth.loginWithMagicLink({ email });
```

I get a 100% CPU load while this "awaits" me clicking on my email. My whole login flow works, I have only this CPU load issue (not very nice for users' batteries & heat ;) ).

Is this something known to other people ? Am I missing something ?

Cheers !

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  8.0.1
| Browser          | Chrome
| `yarn`           | 1.22.17
| Operating System | MacOs

**Comment by Ethella** [comment]
@guillaumervls the behavior you have is not very common, since we haven't received any similar reports before. Theoretically, the relayer does not consume many resources for authentication. Feel free to post your reproducible example here.
