### ISSUE TITLE
magic.oauth.getRedirectResult() In does not return Oauth Access token or other error(s)

### ISSUE THREAD

**Issue by jackie-nguyen** [magiclabs/magic-js#282]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
I am receiving one of two errors when using the Google Oauth with Next JS. These are client side errors and they happen on the callback from Google auth.

When this error happens, I do not receive a DID and cannot authenticate my user.
```
Error: Magic Extension Error (oauth): [server_error] Failed to retrieve OAuth access token.
    at l.createError
```

When this error happens, I still receive a DID and can authenticate my user, but this is an error on Magic's end.
```
TypeError: Cannot destructure property 'verifier' of 'JSON.parse(...)' as it is null.
```

[Description of the bug.]

### 🧩 Steps to Reproduce

Follow the documentation on integrating Oauth Login with Magic SDK

### 🤔 Expected behavior

The Login should succeed every time without errors

### 😮 Actual behavior

The Login does not succeed every time without errors

### 💻 Code Sample

```typescript
export const loginWithOauthGoogle = async () => {
  const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUB_KEY as string, {
    extensions: [new OAuthExtension()],
  });

  await magic.oauth.loginWithRedirect({
    provider: "google",
    redirectURI: `${window.location.origin}/auth/oauth/google`,
  });
};
```

```typescript
export const handleGoogleRedirect = async () => {
  const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUB_KEY as string, {
    extensions: [new OAuthExtension()],
    // testMode: true,
  });

  const res = await magic.oauth
    .getRedirectResult()
    .catch((err) => console.log(err)); // the error is happening here

  if (!res) return new Error("error signing in with google with magic");

  ...
}
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  ^8.0.1
| Browser          | Chrome latest
| `yarn`           | yarn version v1.22.17
| Operating System | macOS Big Sur 11.5.2

**Comment by jackie-nguyen** [comment]
Okay someone from the Discord gave me a bunch of example implementations (which would be nice to have in the Documentation btw)

Okay, this appears to be a mistake on how I was handling the redirect in a next page.

Apparently Magic has an example here:
https://github.com/magiclabs/example-nextjs/blob/master/pages/callback.js

Apparently wrapping the function won't work like this
```typescript
export default function Page() {
  useEffect(() => {
    handleGoogleRedirect()
  }, [])
}
```

This is what ended up not giving me any errors
```typescript
export default function Page() {
  useEffect(() => {
    finishSocialLogin()
  }, [])

  const finishSocialLogin = async () => {
    const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUB_KEY as string, {
      extensions: [new OAuthExtension()],
    });

    let result = await magic.oauth.getRedirectResult();

    doSomethingWithDID(result)
  };
}
```

**Comment by jackie-nguyen** [comment]
If anyone else runs into this, apparently wrapping the redirect in a useCallback will break the oauth login. Adding a wrapper to the dependency array of a useEffect call (to fix lint error: _react-hooks/exhaustive-deps_) will also break it.

**Comment by arnaudjnn** [comment]
@jackie-nguyen I have the same error even if I initialize Magic at the function level. How did you end up?

**Comment by felipeaugusto1** [comment]
I'm also running into the same issue
