### ISSUE TITLE
Solana extension "kitchen sink" example does not work

### ISSUE THREAD

**Issue by spencekim** [magiclabs/magic-js#284]
### 🐛 Description

https://codesandbox.io/s/github/MagicLabs/example-solana

Sending the transfer transaction does not work. 

### 🧩 Steps to Reproduce

1. Log in and verify email.
2. Click sign transaction.
3. Click send transaction.

### 🤔 Expected behavior

The transaction is sent successfully.

### 😮 Actual behavior

The transaction fails. 

<img width="729" alt="Screen Shot 2022-02-27 at 12 50 17 AM" src="https://user-images.githubusercontent.com/19200359/155875421-f6374a55-3310-4543-a1e8-5697b5dab4a6.png">

**Comment by smithki** [comment]
cc @harryEth

**Comment by am-hernandez** [comment]
Hello @spencekim and thank you for opening this issue. We have updated the demo recently that resolves this issue.

I just successfully sent a transaction using the [demo](https://codesandbox.io/s/github/MagicLabs/example-solana) you linked above.
