### ISSUE TITLE
OAuth loginWithRedirect method resolves before redirect

### ISSUE THREAD

**Issue by mightymatth** [magiclabs/magic-js#289]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

A promise returned from `oauth.loginWithRedirect()` method is returned too early before the redirect actually happens.

### 🧩 Steps to Reproduce

1. Have one of OAuth providers enabled
2. execute `oauth.loginWithRedirect()` and wait for result

### 🤔 Expected behavior

The promise from `oauth.loginWithRedirect()` should resolve just as redirect happens (or after, but not far before the redirect happens).

### 😮 Actual behavior

The promise resolves in about 100ms, but the redirect happens for, at least, 1 second after the promise resolves. It breaks the UI if we rely on this promise and we need to do hacks to lengthen it to last until the redirect.

**Comment by am-hernandez** [comment]
Hello @mightymatth and thank you for reporting this issue! You don't have to wait for anything after the `loginWithRedirect()` call, just let it redirect.

Would you please follow up with your specific use case and a minimal reproducible code sample? We will reopen the issue when that has been shared!
