### ISSUE TITLE
Provider's `eth_requestAccounts` lasts too long

### ISSUE THREAD

**Issue by mightymatth** [magiclabs/magic-js#290]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I've noticed that a simple signer call `eth_requestAccounts` lasts for up 1-2 seconds, which is weird. Well, if the user didn't log out or change the account, the address won't ever change. It would be nice if you somehow store it in web3 provider object and retrieve it instantly.

**Comment by am-hernandez** [comment]
Hello @mightymatth , thank you for reporting this issue. Are you still experiencing this behavior? If so, would you please provide a minimal reproducible code sample? 

Closing for now but we will reopen this issue if you follow up with a reproducible code sample.

**Comment by mightymatth** [comment]
Oh, thanks for the response, in an IE11 fashion. It's obvious that you fixed this issue after a year.
