### ISSUE TITLE
testMode does not support Solana

### ISSUE THREAD

**Issue by bmeeder22** [magiclabs/magic-js#292]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When running magic in `testMode: true` with the purpose of creating automated end to end tests. We would like to use test mode's [advanced usage and specify a public/private keypair](https://magic.link/docs/introduction/test-mode#advanced-usage). However when calling `magic.user.getMetadata` we are still getting ETH addresses back. 

### 🧩 Steps to Reproduce

1. Create Magic instance with `testMode: true` and with the `SolanaExtension`
2. Login with `test+success_with_{HUVTyT2A4yP3jkSAA5UKpBCxgbsFYMNXEfeZJ4pDYoTx:632e50d753872bb065eeedcc627ddd26252bb69a2f6a69655baf4488990cf5ebf4c5dbb387de9a2102f1646723abcbcefbd0464c48b19988d81c2f324fdb09cb}@magic.link` which is a solana public/private keypair
3. Call `const user = await magic.user.getMetadata()` and you'll see that `user.publicAddress` is an ethereum address that does not match the public key we passed in. 

### 🤔 Expected behavior

It should match the public key that we passed in. 

### 😮 Actual behavior

Call `const user = await magic.user.getMetadata()` and you'll see that `user.publicAddress` is an ethereum address that does not match the public key we passed in. 

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | `8.0.1`
| Browser          | `Chrome`
| `yarn`           |
| Operating System | `any`

**Comment by bmeeder22** [comment]
Here is an example code sandbox which shows that while using a test email address the Solana Address comes through as an ETH address (starts with 0x). 

https://codesandbox.io/s/nervous-feather-ikqn0d?file=/package.json

**Comment by ayv8er** [comment]
Hello @bmeeder22, thank you for bringing up this feature request! Our documentation currently states that the public address returned from the getMetadata method is associated to the Ethereum blockchain.
