### ISSUE TITLE
Magic RPC Error: [-32603]  loginWithSMS  magic-sdk@8.1.0. Also in earlier versions (6.2.1, 7.0.0, 8.0.1) 

### ISSUE THREAD

**Issue by danlg** [magiclabs/magic-js#305]
### ✅ Prerequisites

- [ x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
not reported
- [ x] Are you running the latest SDK version?
Yes
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
I need loginWithSMS with React / Electron @smithki 
I have tried to amend the example repo :
https://github.com/magiclabs/example-electron @hcote 

[Description of the bug.]

### 🧩 Steps to Reproduce

1. git clone https://github.com/magiclabs/example-electron
2. change in package.json magic-sdk@8.1.0 (not 4.1.1 as the original repo)
3. yarn 
4. yarn start
Replace login.js with: 
```
import React, { useCallback, useState } from 'react';
import { useHistory } from 'react-router';
import { magic } from '../magic';

export default function Login() {
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const history = useHistory();
  const login = useCallback(async () => {
    setIsLoggingIn(true);
    try {
        console.log("login email:magic.auth", magic.auth)
        console.log("magic.version", magic.version)
        await magic.auth.loginWithMagicLink({ email });
      history.push('/');
    } catch {
      setIsLoggingIn(false);
    }
  }, [email]);

  const loginMobile = useCallback(async () => {
    setIsLoggingIn(true);
    try {
      if (magic.auth.loginWithSMS) {
        console.log("loginMobile:magic.auth found !!", magic.auth)
        console.log("magic.version", magic.version)
        await magic.auth.loginWithSMS({ phone});
        history.push('/');
        console.log("loginMobile called", e)
      } else {
        console.log("magic.auth.loginWithSMS", magic.auth.loginWithSMS )
      }
    } 
    catch (e){
        console.log("errorloginWithSMS", e)
        setIsLoggingIn(false);
    }
  }, [phone]);
  /**
   * Saves the value of our email input into component state.
   */
  const handleInputOnChange = useCallback((event) => {
    setEmail(event.target.value);
  }, []);

  const handlePhoneOnChange = useCallback((event) => {
    setPhone(event.target.value);
  }, []);

  return (
    <div className='container'>
      <h1>Please sign up or login</h1>
      <input
        type='email'
        name='email'
        required='required'
        placeholder='Enter your email'
        onChange={handleInputOnChange}
        disabled={isLoggingIn}
      />
      <button onClick={login} disabled={isLoggingIn}>
        Send email
      </button>
      <input
        type='phone'
        name='phone'
        required='required'
        placeholder='Enter your Phone'
        onChange={handlePhoneOnChange}
        disabled={isLoggingIn}
      />
      <button onClick={loginMobile} disabled={isLoggingIn}>
        Send Mobile
      </button>
    </div>
  );
}
```

### 🤔 Expected behavior
be able to receive SMS and login with OTP number received.

### 😮 Actual behavior
For 8.1.0, I have compilation error:
Compiled with warnings.
./node_modules/magic-sdk/dist/es/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

For earlier versions (6.2.1, 7.0.0, 8.0.1) and 8.1.0, I managed to compile without error, and I get the error :
errorloginWithSMS Error: Magic RPC Error: [-32603] Internal error: Cannot read properties of undefined (reading 'trim')
    at base-module.ts:33:1

[What actually happened? Please include any error stack traces you encounter.]

### 💻 Code Sample
see above
### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.1.0
| Browser          | Chrome
| `yarn`           |
| Operating System | Mac

**Comment by danlg** [comment]
I have managed to fix the issue using sdk 6.2.1. The problem was due to the 
magic.auth.loginWithSMS({ phone}) actually the variable name matters and is a shortcut for magic.auth.loginWithSMS({ "phoneNumber": phone}); However the error was not clear at all.

**Comment by Ethella** [comment]
@danlg Hi, thx for reporting the turbulence. I'll relay this back to the team. 😄

**Comment by aoloo** [comment]
@Ethella I hope you are well. I am experiencing an issue with that error code. I created an issue https://github.com/magiclabs/magic-js/issues/30. Do you have any insight on what could be causing this? Thank you for all the work your putting in into this project.
