### ISSUE TITLE
Magic RPC Error: [-10010] Receipient's inbox is not configured to receive emails.

### ISSUE THREAD

**Issue by osequi** [magiclabs/magic-js#311]
### ✅ Prerequisites

- [ x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I'm getting this error for signing in with `test@test.com`.
I couldn't find this error message in the documentation: https://magic.link/docs/api-reference/client-side-sdks/web#errors-warnings
My question is if there are other hidden / undocumented error messages, and if yes, where I can find them?

**Comment by Ethella** [comment]
Hi @osequi, yes, there're undocumented errors. As these errors are more related to end-users, we choose to display them in the modal to direct end-users. If you, as a developer, need to handle these errors separately, please elaborate on your use case and we may discuss it.
