### ISSUE TITLE
Decouple expo web browser from RN ext oauth

### ISSUE THREAD

**Issue by victor-oancea-leftclick-io** [magiclabs/magic-js#313]
### ✨ Feature Request

The oauth RN implementation requires expo-web-browser, which requires expo.

We need to be able to use it on projects that don’t use expo.

## 💻 Examples

https://reactnative.dev/docs/linking#openurl Could be used

**Comment by Ethella** [comment]
Hey @victor-oancea-leftclick-io. I've taken a closer look at all the possible solutions including the one you suggested.

However, with bare RN, I couldn't find a good library that supports both SFAuthsession in iOS and CustomTab in Android, which are the two key components for OAuth2 integrations in our mobile infra to ensure security.

* The `openURL` API from RN  is not feasible, that it only opens a regular browser without handling an authentication session
* [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth), does offer an OAuth solution but it's not customizable for our use case.

So, I would suggest you give it a try to initialize expo modules by `npx install-expo-modules@latest`

For more context, you may check.
https://docs.expo.dev/bare/installing-expo-modules/

Let me know if it helps 😄

**Comment by rcorrie** [comment]
@Ethella have you looked into https://github.com/proyecto26/react-native-inappbrowser ?

**Comment by rcorrie** [comment]
@ice-ares feel free to try my PR

**Comment by magiclabsFE** [comment]
:rocket: Issue was released in [`@magic-ext/algorand@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/algorand%408.1.0), [`@magic-ext/avalanche@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/avalanche%408.1.0), [`@magic-ext/bitcoin@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/bitcoin%408.1.0), [`@magic-ext/conflux@6.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/conflux%406.1.0), [`@magic-ext/connect@6.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/connect%406.1.0), [`@magic-ext/cosmos@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/cosmos%408.1.0), [`@magic-ext/ed25519@4.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/ed25519%404.1.0), [`@magic-ext/flow@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/flow%408.1.0), [`@magic-ext/harmony@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/harmony%408.1.0), [`@magic-ext/icon@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/icon%408.1.0), [`@magic-ext/near@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/near%408.1.0), [`@magic-ext/oauth@7.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/oauth%407.1.0), [`@magic-ext/polkadot@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/polkadot%408.1.0), [`@magic-ext/react-native-bare-oauth@7.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-bare-oauth%407.1.0), [`@magic-ext/react-native-expo-oauth@7.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-expo-oauth%407.1.0), [`@magic-ext/solana@9.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/solana%409.1.0), [`@magic-ext/taquito@5.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/taquito%405.1.0), [`@magic-ext/terra@5.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/terra%405.1.0), [`@magic-ext/tezos@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/tezos%408.1.0), [`@magic-ext/webauthn@7.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/webauthn%407.1.0), [`@magic-ext/zilliqa@8.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/zilliqa%408.1.0), [`@magic-sdk/commons@9.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/commons%409.1.0), [`@magic-sdk/pnp@7.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/pnp%407.1.0), [`@magic-sdk/provider@13.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/provider%4013.1.0), [`@magic-sdk/react-native-bare@13.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-bare%4013.1.0), [`@magic-sdk/react-native-expo@13.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-expo%4013.1.0), [`@magic-sdk/types@11.1.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/types%4011.1.0), [`magic-sdk@13.1.0`](https://github.com/magiclabs/magic-js/releases/tag/magic-sdk%4013.1.0) :rocket:
