### ISSUE TITLE
Callback URL is stripped from query parameters

### ISSUE THREAD

**Issue by vertti** [magiclabs/magic-js#314]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Setting a callback url returns you back to that URL but if the URL had query parameters, those are removed.

### 🧩 Steps to Reproduce

```
    const didToken = await magic.auth.loginWithMagicLink({
      email: watch().email,
      redirectURI: new URL('/magic/callback?returnpath=foobar', window.location.origin).href,
    })
```
With the above setting of `redirectURI`, I would expect to return to URL:

```
https://mysite.com/magic/callback?returnpath=foobar&magic_credential=WyIweDExN2E4......
```
but instead the returning URL is:
```
https://mysite.com/magic/callback?magic_credential=WyIweDExN2E4......
```

### 🤔 Expected behavior

It would be convenient to be able to pass query parameters with the callback URL. For example in my case, the phase of the wizard the user should be returned to after login.

### 😮 Actual behavior

Query parameters are stripped from callback URL.

### 💻 Code Sample

Take the NextJS example project and change callbackURL to contain query parameters.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  8.1.1
| Browser          | Chrome  101.0.4951.54
| `yarn`           | npm 8.1.2
| Operating System | MacOS 12.3

**Comment by Ethella** [comment]
@vertti This feature has been considered and the ETA will be roughly by this quarter
