### ISSUE TITLE
The request 'process/browser' failed to resolve only because it was resolved as fully specified with webpack 5 and CRA

### ISSUE THREAD

**Issue by davzb** [magiclabs/magic-js#315]
Hello,

I tried to implement magic with Solana extension into react 18 and webpack 5. I created webpack config to install some polyfill but I am still getting this error:

```
ERROR in ./node_modules/@magic-sdk/provider/dist/es/index.mjs 240:16-23
Module not found: Error: Can't resolve 'process/browser' in 'C:\Users\...\node_modules\@magic-sdk\provider\dist\es'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Did you have similar issue and did you correct it, kinda lost right now with this issue.
Thank you guys

**Comment by Ethella** [comment]
Could you provide a reproducible example?

**Comment by kobibarhanin** [comment]
Same here, not sure how to provide an example for you, while working on sdk version 4 everything was ok, upgrading to version 9 gave me this issue (I think version 6 was the earliest to present this issue).

**Comment by rbrisita** [comment]
Having the same issue. Seems to stem from CRA v5+ and accessing polyfills because webpack 5 doesn't include them anymore.

**Comment by rbrisita** [comment]
Following these instructions:

https://alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5

And adding:
`"process/browser": require.resolve("process/browser"),`

in the Object.assign secton of the `config-overrides.js` file seems to have fixed it.
