### ISSUE TITLE
loginWithMagicLink swallows events on Safari

### ISSUE THREAD

**Issue by johanneskares** [magiclabs/magic-js#320]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

On Safari I'm not able to create a loading animation when the user signs in.

### 🧩 Steps to Reproduce

1. Open Codesandbox on Safari: https://codesandbox.io/s/objective-poitras-cxlu06?file=/src/App.js
2. Put in Magic.Link Key
3. Click on both buttons

### 🤔 Expected behavior

When I click `Sign In / Up` I expect to see `Is Loading: True` at the top.

### 😮 Actual behavior

The loading variable doesn't update. The Magic SDK blocked the UI somehow.

### 💻 Code Sample

(https://codesandbox.io/s/objective-poitras-cxlu06?file=/src/App.js)

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.1.1
| Browser          | Safari

**Comment by johanneskares** [comment]
If found a workaround: Call `magic.preload()` on startup. I guess this should be documented somewhere.

**Comment by Ethella** [comment]
Thx for the feedback. Will take a look!
