### ISSUE TITLE
[DESCRIPTIVE FEATURE NAME]

### ISSUE THREAD

**Issue by JoaoCampos89** [magiclabs/magic-js#326]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Magic should allow custom UTXO blockchains as similar to EVM

## 🧩 Context

I would like to start use magic login for custom UTXO blockchains similar to BTC like for instance Dogecoin. Magic signature should allow a custom configuration and rpc to allow any UTXO based chain to be used to be signed by magic.

## 💻 Examples

Use Dogecoin or LTC

**Comment by ayv8er** [comment]
Thank you for the feature request suggestion. Should we ever consider this request, we will reopen this issue.
