### ISSUE TITLE
React-Native user authentification check takes a lot of time

### ISSUE THREAD

**Issue by pisarevkir** [magiclabs/magic-js#329]
### ✅ Prerequisites

- [✅] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [✅ ] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

We have several questions regarding the authentification process with magic, in particular how to handle the authentification status check on app startup (react-native app). Do you have any best practices about that? 

Here is how we do it now when the app is loaded:
1. Check if user is logged in via `magic.user.isLoggedIn()`
2. If yes -> `magic.user.getIdToken()` and `magic.user.getMetadata()` in parallel

The problem is that the first request takes from 3 to 5 seconds and the second pair also takes from 3 to 5 seconds to receive data. So users have to wait ~10 secs every time they open the app. Is any chanse we can speed up that process / change the flow?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | "@magic-sdk/react-native": "^8.2.1"
| Operating System | react-native / iOS / Android

**Comment by Ethella** [comment]
Hi @pisarevkir, thank you for your feedback. Generally, calls combined should only take around 2~3s. Do you mind sharing your rough location so we can check if it's related?

**Comment by pisarevkir** [comment]
Hi @Ethella! 
We tried to execute those requests from Romania, Russia, Ukraine.
And the first step - `magic.user.isLoggedIn()` takes from 2s to 5s.
The second step for authorized users takes slightly less time, from ~1.5 to 4 secs:
```
Promise.all([
      magic.user.getIdToken(),
      magic.user.getMetadata(),
])
```

Just wonder if it's viable solution to get rid of the `magic.user.isLoggedIn` part and make a decision if user is logged-in depending on either `magic.user.getIdToken` returns error with some specific code or actual token string?
