### ISSUE TITLE
Magic React Native won't accept any custom networks

### ISSUE THREAD

**Issue by daweth** [magiclabs/magic-js#331]
### ✅ Prerequisites

- [ x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ x] Are you running the latest SDK version?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When creating a magic instance in a react native app, passing in custom network params breaks the entire instance. Any calls made with the magic instance (such as loginWithMagicLink) will hang forever. 

### 💻 Code Sample

```

const avaxFujiOptions = {
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    chainId: 43113,
};

export const magicAvaxFuji = new Magic(
    REACT_APP_MAGIC_PUBLISHABLE_KEY,
    { network: avaxFujiOptions }
 );
```

**Comment by Ethella** [comment]
Tested it again with your setup, and the issue you mentioned didn't happen. Could you double-check if your iframe started properly? You may investigate it via `Safari -> Develop -> Your Device -> box.magic.link`
