### ISSUE TITLE
@magic-sdk/react-native 9.0.0 - expo-modules-core error

### ISSUE THREAD

**Issue by ginnymin** [magiclabs/magic-js#340]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I was prompted to bump up to 9.0.0 from 8.2.1 over the weekend. When I tried, I kept running into the error `Unable to resolve module expo-modules-core` when running my app. When I downgraded back down to 8.2.1, the error went away and my app loaded.

When digging around I noticed that the dependency `expo-application` was the origin of the error, and that `expo-application` was added as a dependency to `@magic-sdk/react-native` between 8.2.1 and 9.0.0. When looking at the PRs #335 #337 #338, `expo-application` was added alongside the devDependency `expo-modules-core` and peer dependency `expo`. However, the package.json in its current state only has `expo-application` added, and I'm guessing this is what's causing the error I'm seeing.

A side question - Is it expected that `expo` is going to be required for `@magic-sdk/react-native`? My app does _not_ use `expo` so I'm curious about where this is going.

**Comment by ginnymin** [comment]
OK, I must have been reading old documentation, I just noticed the README updates stating that you'll only be supporting expo going forward. Closing this.

**Comment by dgerrellsMagic** [comment]
Hi @ginnymin, I do want to note that at this time we are only supporting expo but do intend to bring raw react native support back in the future. @Ethella Please correct me on this if I am wrong here.

**Comment by Ethella** [comment]
@ginnymin, You may still use `8.x` versions for bare RN. And like what @dgerrellsMagic said, we do want to bring back the bare-RN support with bare-RN OAuth in the future.

**Comment by ginnymin** [comment]
@dgerrellsMagic @Ethella thanks for the clarification!
