### ISSUE TITLE
Redirect URI query string garbled on email login redirect

### ISSUE THREAD

**Issue by ariboren** [magiclabs/magic-js#341]
# CRITICAL: BROKEN IN PRODUCTION

### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Starting on July 26, Magic changed the formatting of redirect URIs: previously, I was able to pass a `redirectURI` with query params, which would be correctly combined with the `magic_credential` prior to redirect. Now, query params included in `redirectURI` are encoded, and the additional params added by Magic are included as a new query string. **This is breaking routing in our Next.js app in our critical user authentication flow.**

### 🧩 Steps to Reproduce

1. Pass a URL with a query string when logging in:
```js
 Magic.login({
    email': 'email@company.com',
    key: magicPubKey,
    redirectURI: 'https://someUrl.com?loginAttempt=12345',
}),
```
2. Open magic link from email
3. Observe incorrectly formatted redirect URL on auth success: `'https://someUrl.com%3FloginAttempt%3D12345?magic_credential=<credential>`

I can confirm that the payload passed to  Magic includes the full original URL as intended:
<img width="467" alt="Screen Shot 2022-08-02 at 1 25 27 PM" src="https://user-images.githubusercontent.com/3615404/182436829-6cc84d32-aac8-41fd-a2d4-1ceba4311f7a.png">
<img width="761" alt="Screen Shot 2022-08-02 at 1 25 33 PM" src="https://user-images.githubusercontent.com/3615404/182436839-c5b8256f-9559-4c7f-94f9-68025587954b.png">

### 🤔 Expected behavior

The `magic_credential` should be added to existing query params in the URL.

### 😮 Actual behavior

Existing query params are encoded, and `?magic_credential=...` appended.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.1.1
| Browser          | All

**Comment by ayv8er** [comment]
Thank you for bringing this to our attention, we'll have this resolved and update here.

**Comment by ayv8er** [comment]
@ariboren We've deployed a fix to this issue. Thank you for bringing this up.
