### ISSUE TITLE
Can i open social login option in popup instead of redirecting to new url?

### ISSUE THREAD

**Issue by VarshaZbyte** [magiclabs/magic-js#343]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I am adding social login option to my application. But on selecting provider, it is redirecting me to provider's login screen. I want this screen to get opened in my application context or in small pop-up. I don't want to get redirected to new URL.
Could you please help mw with the same?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.1.1
| Browser          | chrome
| `yarn`           |
| Operating System | Windows

**Comment by ayv8er** [comment]
@VarshaZbyte Thank you for bringing up this feature request. I'll make sure it gets through to our Product team so it can be considered to be a part of our roadmap.
