### ISSUE TITLE
"This login was requested using None, None..."

### ISSUE THREAD

**Issue by ginnymin** [magiclabs/magic-js#347]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I'm using the Magic SDK with bare react native (8.2.1) and I notice the text `This login was requested using None, None...` at the bottom of the login emails. My question is - where is the `None, None` coming from and is it possible to change it? I tried searching the docs and the issues and couldn't find anything.

<img width="428" alt="Screen Shot 2022-08-14 at 4 23 01 PM" src="https://user-images.githubusercontent.com/438281/184555418-ec8dcf3d-c0d1-4a0e-92b6-bddd735a7473.png">

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-sdk/react-native`      | 8.2.1

**Comment by am-hernandez** [comment]
Hello @ginnymin , thank you for reporting this issue. 

It looks like the user-agent header couldn't be resolved because it was missing. Including the appropriate header will fix this issue.

**Comment by ginnymin** [comment]
@am-hernandez how would I go about including that? I'm just using the loginWithMagicLink method

**Comment by am-hernandez** [comment]
Hi @ginnymin , would you happen to be using an emulator? I don't know how you'd get it to show up with all web requests from the emulator but it should be possible.

**Comment by ginnymin** [comment]
I first noticed it when logging in from a real device (both android and iOS) but I think I also see it when logging in from the simulator.

**Comment by am-hernandez** [comment]
Hi @ginnymin Would you please try again from your Android and iOS device just to verify the user agent is still missing when using the actual mobile device? I am reopening this issue in the meantime.

**Comment by ginnymin** [comment]
@am-hernandez Thanks for looking further into this! I just tried from my physical iOS device and the email still says "None, None":

<img width="435" alt="Screen Shot 2022-09-04 at 12 42 56 PM" src="https://user-images.githubusercontent.com/438281/188326557-e85fb7b0-648d-4ca7-9ab5-7e0cf25a8e0b.png">

**Comment by ilyavf** [comment]
Same issue with both iOS simulator and iPhone device.

**Comment by joshuascan** [comment]
Closing this out as it has been resolved in subsequent versions. Thanks!
