### ISSUE TITLE
Error: [-32603] Internal error: User denied account access

### ISSUE THREAD

**Issue by OlehPanforov** [magiclabs/magic-js#348]
### ✅ Prerequisites

- [+] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [+] Are you running the latest SDK version?
- [+] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When we call magic.user.getIdToken() or magic.user.getMetadata(), we get the error:
`code: -32603
jsEngine: "hermes"
message: "Magic RPC Error: [-32603] Internal error: User denied account access."
rawMessage: "Internal error: User denied account access."
stack: "Error: Magic RPC Error: [-32603] Internal error: User denied account access.\n    at construct (native)\n 
`

### 🧩 Steps to Reproduce

1. Login: 
```
magic.auth.loginWithMagicLink({
   email,
})
```
or 
```
magic.auth.loginWithSMS({
   phoneNumber: phone,
});
```
or
```
magic.oauth.loginWithPopup({
   provider,
   redirectURI: `${ENV.MAGIC_DEEPLINK_SCHEME}://login`,
});
```
2. Call `magic.user.getMetadata();`, all good we can get metadata.issuer from getMetadata result,
3. Close the app (unload from memory)
4. Open the app again
5. Call on start
```
const [token, metadata]: [string, MagicUserMetadata] = yield Promise.all([
   magic.user.getIdToken(),
   magic.user.getMetadata(),
]);
```
6. Promise fails with error 
`[-32603] Internal error: User denied account access.`

### 🤔 Expected behavior

We expect to get the token from getIdToken() and metadata from getMetadata() after app relaunch

### 😮 Actual behavior

We get the error 
`code: -32603
jsEngine: "hermes"
message: "Magic RPC Error: [-32603] Internal error: User denied account access."
rawMessage: "Internal error: User denied account access."
stack: "Error: Magic RPC Error: [-32603] Internal error: User denied account access.\n    at construct (native)\n 
`

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.2.1
| React Native      |   0.68
| `yarn`           |  1.22.18
| Operating System | iOS

**Comment by ayv8er** [comment]
@OlehPanforov Thank you for bringing this to our attention. This is a known issue that's been brought up in a previous GitHub issue# 279. We'll be posting updates on that issue.
