### ISSUE TITLE
Unsupported Magic Connect method for isLoggedIn call

### ISSUE THREAD

**Issue by kobibarhanin** [magiclabs/magic-js#350]
I'm getting: 
`login error:  Error: Magic RPC Error: [-32603] Internal error: Unsupported Magic Connect method.`

for this code:

```
const magicAuth = new Magic(...)
await magicAuth.user.isLoggedIn()
```

with these versions:

"magic-sdk": "9.0.0"
"@magic-ext/connect": "2.0.2",

**Comment by am-hernandez** [comment]
Hi @kobibarhanin , thank you for submitting this issue. Please check that you are only calling Magic Connect methods in a Magic Connect app. This error comes from a mismatch of calling Magic Auth methods with a Magic Connect instance. You can see the supported SDK methods here in [Magic Connect - Docs](https://magic.link/docs/connect/connect-sdk/api-reference).
