### ISSUE TITLE
localforage as peerDependency

### ISSUE THREAD

**Issue by mbret** [magiclabs/magic-js#351]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Consider adding localforage as peerDependency

## 🧩 Context

Currently there is a duplicate localforage injection if main app is using different version of localforage when bundling. It would be better for bundle size if generic packages like this one was a peer dependency

## 💻 Examples

No example

**Comment by am-hernandez** [comment]
Hello @mbret , thank you for the feature request! I am going to share this with our Product team so that it may be added to our roadmap.

**Comment by dgerrellsMagic** [comment]
@mbret Can you expand on what you are seeing here? What do you mean on "duplicate localforage injection"?
