### ISSUE TITLE
What is the expected argument for Solana Extension signMessage function?

### ISSUE THREAD

**Issue by jp-melanson** [magiclabs/magic-js#354]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Why the signMessage function always throws this error?

```
 [Error: Magic RPC Error: [-32603] Internal error: unexpected type, use Uint8Array]
```

I've been trying to invoke it using a `string` as well as a `Uint8Array` but no luck.
The Uint8Array is created from `tweetnacl-ts` lib's `decodeUTF8` function.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | "@magic-sdk/react-native": "^10.0.0",
| solana extension | "@magic-ext/solana": "^5.0.0",
| Browser          | NA
| `npm`           | 8.18.0
| Operating System | MacOS 12.5.1

**Comment by am-hernandez** [comment]
Hello @jp-melanson , thank you for reporting this issue. The expected argument is `Uint8Array`. Here is a working code snippet:

```javascript
const signAndVerify = async () => {
    const message = "Hello";
    const encodedMsg = decodeUTF8(message);
    const signature = await magic.solana.signMessage(encodedMsg);

    const verifiedMsg = nacl.sign.detached.verify(
      encodedMsg,
      signature,
      base58_to_binary(userMetadata.publicAddress)
    );
    console.log("Sig verified:", verifiedMsg);
  };
```

You may also check out this working [Codesandbox demo](https://codesandbox.io/s/ma-otp-forked-8yt5e7?file=/src/components/Profile.js).
