### ISSUE TITLE
@magic-sdk/provider EthNetworkName missing "goerli"

### ISSUE THREAD

**Issue by VladimirMikulic** [magiclabs/magic-js#363]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

@magic-sdk/provider EthNetworkName is missing "goerli".

![Screenshot_20220927_190755](https://user-images.githubusercontent.com/35997844/192591374-6bc8e2f1-f939-48e5-a612-976e32acf591.png)

![Screenshot_20220927_191102](https://user-images.githubusercontent.com/35997844/192592075-53e4942c-3c1f-4fe1-8619-261323d63ea9.png)

## 🧩 Context

![Screenshot_20220927_191236](https://user-images.githubusercontent.com/35997844/192592223-778649c0-e419-456b-ac98-fec9d739c354.png)

**Comment by harryEth** [comment]
Thanks for opening this issue. it got fixed in `magic-sdk@9.1.1`.

closing this issue.

**Comment by VladimirMikulic** [comment]
Wow. That was fast. Thanks a lot @harryEth!
