### ISSUE TITLE
Provide a method to cancel current login request

### ISSUE THREAD

**Issue by ilyavf** [magiclabs/magic-js#365]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Provide a method that can cancel the current login request initiated with `loginWithMagicLink({ ..., showUI: false })`.

## 🧩 Context

In the out-of-the-box Magic UI there is an option to change the email. In this case SDK throws the error 1005:
```
-10005  UserRequestEditEmail  The user has stopped the login request because they want to edit the provided email.
```
I am not using the built-in UI, so I need a method to cancel the current request in this case by myself.

## 💻 Examples

After I initiate the login request:
```
const m = new Magic('API_KEY');
try {
  await m.auth.loginWithMagicLink({ email: 'hello@example.com', showUI: false });
} catch {
  // Handle errors if required!
}
```

I would like to have a UI control that can cancel it. E.g. by calling a method like:
```
m.auth.requestEditEmail();
// or more generic:
m.auth.cancelLoginRequest();
```

**Comment by ayv8er** [comment]
@ilyavf Thank you for bringing this to our attention. I'll make sure this feature request is brought up to our Product team.

**Comment by paro-paro** [comment]
Yes, right now there is no UX friendly way to stop `loginWithMagicLink({ ..., showUI: false })` flow!

So +1 for this feature request!

**Comment by fablanglet** [comment]
+1
Do you have an eta to implement ?

**Comment by ayv8er** [comment]
We plan on releasing this feature before end of year.
Once the feature is out, the event will be included in our docs [here](https://magic.link/docs/api/client-side-sdks/web#events).
Thank you all for your patience!
