### ISSUE TITLE
`magic.user.isLoggedIn()` returns false for OAuth authentications after app is restarted

### ISSUE THREAD

**Issue by rcorrie** [magiclabs/magic-js#367]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] ~Are you running the latest SDK version?~ _(See Description)_
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Since I am building a RN app without Expo, I need to run the following versions:

```
@magic-ext/react-native-oauth: 2.0.0
@magic-sdk/react-native: 8.0.0
```

Everything works find with the email link authentication.

With OAuth authentication (testing with google), the app authenticates fine initially. If I kill the app and re-launch it, the user is no longer signed in.

### 🧩 Steps to Reproduce

1. Run your app using the lib versions stated above
2. Login using google oauth
3. Kill and reopen app

### 🤔 Expected behavior

`magic.user.isLoggedIn() === true`

### 😮 Actual behavior

`magic.user.isLoggedIn() === false`

### 💻 Code Sample

N/A

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `react-native` | 0.70.1
| `@magic-sdk/react-native`      | 8.0.0
|`@magic-ext/react-native-oauth`         | 2.0.0
| Operating System | iOS 15.4.1

**Comment by am-hernandez** [comment]
Hi @rcorrie, thank you for reporting this issue. This is a known issue that's been brought up in a previous GitHub issue #279 . We'll be posting updates on that issue's thread.
