### ISSUE TITLE
Not possible to add a Domain/Mobile Access Whitelist for bare React Native?

### ISSUE THREAD

**Issue by ginnymin** [magiclabs/magic-js#370]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I got an email recently that stated we needed to add a domain whitelist by October 31st or else service would not work.

I'm using Magic with a bare React Native app (not Expo) so I am on version 8.x. When I tried to edit the Whitelist section of my settings, I see the following messaging:

<img width="759" alt="Screen Shot 2022-10-05 at 8 21 40 PM" src="https://user-images.githubusercontent.com/438281/194192967-a88708ae-bed7-4a6b-abd5-6b6bace54d1f.png">

Stating that I can only do this if I have 9.0.0+ and Expo (which I do not have).

Is it possible for me to add whitelist information for my application? Or is it not possible and I will have to switch to another service and reconfigure my app at the last hour?

**Comment by ayv8er** [comment]
We'll be bringing this up for internal discussion this week.
I'll provide an update on how we plan on addressing this.

**Comment by ginnymin** [comment]
@ayv8er thanks for the reply! Definitely update me on this as I would prefer to keep using Magic for auth if possible, but if it is not possible then I will need to start the process of replacing it ASAP. I'm sure I'm not the only person in this situation as well.

**Comment by ayv8er** [comment]
The email you recently received only pertains to web applications.
Web apps would have to enable Whitelist Domains and save their domains.
This is not the case for Whitelist Mobile App setting, this will not be required.
