### ISSUE TITLE
Update type signature of RpcProviderModule to implement Ethers's AbstractProvider

### ISSUE THREAD

**Issue by charesbast** [magiclabs/magic-js#373]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Similar to https://github.com/magiclabs/magic-js/issues/83, we have the same problem with ethers library: `magic.rpcProvider` type does not match the expected param type of `ethers.providers.Web3Provider` constructor.

<img width="1986" alt="Capture d’écran 2022-10-13 à 17 29 46" src="https://user-images.githubusercontent.com/6103456/195639984-eda08b73-b094-4e7f-a825-d46ae6f795dd.png">

### 🤔 Expected behavior

Being able to write `const provider = new ethers.providers.Web3Provider(magic.rpcProvider);` without a compilation error

### 💻 Code Sample
```
const magic = new Magic('PUBLIC_API_KEY');
const provider = new ethers.providers.Web3Provider(magic.rpcProvider);
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 10.0.0
| `ethers`            | 5.7.1
| Browser          | chrome version 106.0.5249.103
| `yarn`           | 3.2.0
| Operating System | macbook pro 2021 16"

**Comment by am-hernandez** [comment]
Hi @charesbast and thank you for submitting this issue. I've gone ahead and marked this as a feature request. Will update this thread when we implement the requested changes!

**Comment by grabbou** [comment]
Hey! I am seeing this issue with the latest Magic SDK & React Native. Are you sure @am-hernandez this was a feature request, not an actual bug? It seems that this is recommended way of setting things up, as per your documentation. Current workaround is to cast to `any`, but that is far from ideal.

**Comment by lantelyes** [comment]
@am-hernandez  this is still an issue...
