### ISSUE TITLE
Avoid replacing the whole query string in loginWithCredential API

### ISSUE THREAD

**Issue by nftsmasher** [magiclabs/magic-js#378]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

If ```loginWithCredential``` gets invoked without a parameter, the existing logic looks for the credential from query string.
It then removes the whole query string instead of removing only ```magic_credential```. 
Any app specific query string gets lost because of this.

### 🧩 Steps to Reproduce

1. Start an application that uses magic link but also has a query string in its url
2. Pass this url as a redirect url when authenticating using magic link
3. Use loginWithCredential from the page where the redirect is happening

### 🤔 Expected behavior

The application specific query string to persist 

### 😮 Actual behavior

The whole query string gets removed

Example:
> https://nftsmasher.com/connect-account?redirect=account&magic_credential=3adflkjfiasdfjask34324kadskjdska....

becomes
> https://nftsmasher.com/connect-account

#### Fix
Replace 
https://github.com/magiclabs/magic-js/blob/000a2a4fd91b5d94a0a31bf0ebb0f11983abcad0/packages/%40magic-sdk/provider/src/modules/auth.ts#L78

with the following code:
```js
const query = new URLSearchParams(credentialResolved)
// remove magic_credential from query string as a precaution.
query.delete('magic_credential')

const urlWithoutMagicCredential = `${window.location.origin}${window.location.pathname}?${query}`
window.history.replaceState(null, '', urlWithoutMagicCredential)
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | latest
| Browser          | chrome
| `yarn`           | latest
| Operating System | mac

### Impact
Web only. Not a critical issue. Has a workaround. 

### Workaround
Passing the query string (```window.location.search```) explicitly as a parameter to ```loginWithCredential``` avoids this problem

**Comment by am-hernandez** [comment]
@nftsmasher Thank you for reporting this issue with the template! This looks like a feature request so i marked it as one. I will share this with our Product team so we can discuss it further.
