### ISSUE TITLE
Magic RPC Error: [-32603] Internal error: eip-1559 transactions don't support gasPrice

### ISSUE THREAD

**Issue by KholdStare** [magiclabs/magic-js#380]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Sporadically I receive an error like

"Magic RPC Error: [-32603] Internal error: eip-1559 transactions don't support gasPrice"
![image](https://user-images.githubusercontent.com/836110/198409797-b83aaba5-0e0e-4b3b-9f60-29d4ca793660.png)

This is bizarre, why is magic still using the legacy `gasPrice` when `max_priority_fee_per_gas` and `max_fee_per_gas` should be used?

### 🧩 Steps to Reproduce

This happens sporadically. Some transactions work, and some don't.

### 🤔 Expected behavior

Properly send eip-1559 transactions

### 😮 Actual behavior

Error inside `base-module.ts:33:1` of `Magic RPC Error: [-32603] Internal error: eip-1559 transactions don't support gasPrice`

### 💻 Code Sample

N/A

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 10.0.0
| Browser          | Brave 1.44
| `yarn`           | 3.1.1
| Operating System | Windows 11

**Comment by am-hernandez** [comment]
Hi @KholdStare and thank you for reporting this issue. You will need to include a `gasPrice` in your transaction object in order for it to send as a non-EIP-1559 transaction. Include the `gasPrice` and you won't face this error.
