### ISSUE TITLE
magic.oauth.loginWithPopup for Web

### ISSUE THREAD

**Issue by mikeavvad** [magiclabs/magic-js#381]
### ✨ Feature Request

Create `magic.oauth.loginWithPopup` for Web

## 🧩 Context

Now for social logins it's only possible to use `magic.oauth.loginWithRedirect` which doesn't cover all cases.
I have an application that is injected to other apps as a library and I wanna do login inside my app without reloading the whole parent app. I feel like `magic.oauth.loginWithPopup` will cover this case.

## 💻 Examples

`magic.oauth.loginWithPopup` in React-native magic lib works exactly like needed.

**Comment by sagarjeu** [comment]
magic.oauth.loginWithPopup({  
provider: 'google',
redirectURI:'***'}) 
not workgin for react native

**Comment by faillacec** [comment]
Required feature for web oauth, the same thing happened, is necessary to have oauth login option without reloading whole app losing context on injected libraries

**Comment by am-hernandez** [comment]
Hi @mikeavvad ,

Thank you for posting this feature request. We did have a chance to go over this request and do not have plans to add it to our roadmap in the immediate future, but will revisit it at a later date!

Thank you!
