### ISSUE TITLE
Magic Auth Web:  magic.user.getMetadata returns different publicAddress for same user email when connecting to "goerli" network

### ISSUE THREAD

**Issue by paro-paro** [magiclabs/magic-js#382]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I would like to implement Magic Auth Web (magic-sdk) in a Vuejs dapp. However, while doing some local testing of the sdk, I have come across the following issue which I will like to understand before I proceed further...

### 🧩 Steps to Reproduce

1. Create 3 magic instances:
- m1: connected to ethereum mainnet network
- m2: connected to goerli network (using options.network = "goerli") - from [docs](https://magic.link/docs/auth/blockchains/ethereum/javascript#use-different-networks)
- m3: connected to goerli network (using options.network.rpcUrl) - `https://goerli.infura.io/v3/${process.env.VUE_APP_INFURA_ID}`

2. Trigger login flow for every magic instance USING SAME EMAIL.
```
async function login(magic) {
  await magic.auth.loginWithMagicLink({ email });
  const data = await magic.user.getMetadata();
  console.log(data.publicAddress);
  await magic.user.logout();
}

async function loginTrigger() {
  await login(m1);
  await login(m2);
  await login(m3);
}
```
3. Log all 3 public addresses.

### 🤔 Expected behaviour

I will expect to get the same public address for the three user cases (since I am using the same email).

### 😮 Actual behaviour

Getting two different public addresses.

- For m1 (Ethereum) and m3 (Goerli with custom rpcUrl) I am getting the same address (as expected) (`0xc4164a4a7a759a4cd947452577381ca660e9609d`)

- For m2 (Goerli with network = "goerli" from docs) I am getting a different one (`0x788552cdecc1f1339d34852eec02b20992fdc77e`)

I have properly registered myself in the Magic Dashboard, created a new app and retrieved the public api key (pk_live_XXX).

I have also run the same code using other custom rpcUrl's such as Celo, Alfajores, Gnosis and Sokol.

In all those cases I am getting `0xc4164a4a7a759a4cd947452577381ca660e9609d` as the public address so... why is the m2 user case returning a different address? Is it a bug? Am I forgetting something, maybe?

Any help will be highly appreciate it! And, of course, thanks in advanced and congrats on this amazing library!

P.S. Likewise, I have used the ethers library to log into the browser the provider.getNetwork() function (getting the expected output for each magic instance) (check attached image below).

### 💻 Code Sample

```
<script>
import { Magic } from "magic-sdk";
import { ethers } from "ethers";

const email = process.env.VUE_APP_MY_EMAIL;

const m1 = new Magic(process.env.VUE_APP_MAGIC_KEY); // ethereum
const m2 = new Magic(process.env.VUE_APP_MAGIC_KEY, { network: "goerli" }); // goerli (from magic docs)
const m3 = new Magic(process.env.VUE_APP_MAGIC_KEY, {
  // goerli (using infura node)
  network: {
    rpcUrl: `https://goerli.infura.io/v3/${process.env.VUE_APP_INFURA_ID}`
  }
});

async function login(magic) {
  await magic.auth.loginWithMagicLink({ email });
  const data = await magic.user.getMetadata();
  console.log(data.publicAddress);
  await magic.user.logout();
}

async function loginTrigger() {
  await login(m1);
  await login(m2);
  await login(m3);
}

const provider1 = new ethers.providers.Web3Provider(m1.rpcProvider);
provider1.getNetwork().then(network => {
  console.log(network);
});

const provider2 = new ethers.providers.Web3Provider(m2.rpcProvider);
provider2.getNetwork().then(network => {
  console.log(network);
});

const provider3 = new ethers.providers.Web3Provider(m3.rpcProvider);
provider3.getNetwork().then(network => {
  console.log(network);
});

export default {
  name: "App",
  methods: {
    click() {
      loginTrigger();
    }
  }
};
</script>

```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 10.0.0
| Browser          | chrome Version 107.0.5304.87 (Official Build) (x86_64)
| `npm`           | 6.14.15
| Operating System | macOs Catalina 10.15.17

![Screenshot 2022-11-05 at 03 24 20](https://user-images.githubusercontent.com/43136874/200097006-2bd24569-9b5b-4453-b261-0a46ddc50a9f.png)

**Comment by ayv8er** [comment]
Hello @paro-paro, what you observed is expected behavior.
Here are 4 possible ways to instantiate Magic.

1. const magic = new Magic(pk_live_A7D9211D7547A338) // mainnet
2. const magic = new Magic(pk_live_A7D9211D7547A338, { network: "mainnet" }) // mainnet
3. const magic = new Magic(pk_live_A7D9211D7547A338, { network: customNode }) // mainnet
4. const magic = new Magic(pk_live_A7D9211D7547A338, { network: "goerli" }) // testnet

The first 3 ways will map to one set of public addresses, while the 4th way will map to a separate set.

The first 2 are essentially the same because `network: "mainnet"` is default if no network is passed into the constructor.
The 3rd way always maps to mainnet even if the custom node is on the goerli network since we wouldn't be able to differentiate.

Your m1 represents the 1st or 2nd way, while m2 represents the 3rd way.
Therefore, they will map to the same set of public addresses.
```For m1 (Ethereum) and m3 (Goerli with custom rpcUrl) I am getting the same address (as expected) (0xc4164a4a7a759a4cd947452577381ca660e9609d)```

Your m2 represents the 4th way, which will map to a separate set of public addresses.
```For m2 (Goerli with network = "goerli" from docs) I am getting a different one (0x788552cdecc1f1339d34852eec02b20992fdc77e)```

**Comment by paro-paro** [comment]
Thanks @ayv8er !

Two different sets of public addresses, got it!
