### ISSUE TITLE
How to listen to wallet connected changes?

### ISSUE THREAD

**Issue by SpadarShut** [magiclabs/magic-js#384]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I'm using magic connect and need to show a widget if a wallet is connected. Howewer I found some problems with getting the correct state of connected wallet:
- If a wallet was connected, I can check wor connected wallets, but if a connection is expired users will see a full screen modal asking them to log in. **How can I at least silently fail if a connection is expired?**
- If a wallet was disconnected via the Connect UI (the Log out link in the widget), **how can I get notified that there is no longer a connected wallet?**

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 10
| Browser          | Chrome
| Operating System | MacOS

**Comment by am-hernandez** [comment]
Magic Connect doesn't support firing events to let a developer know that a user has logged out. However, this feature is coming!

For now, if an action requires a user to be connected, you can call `magic.connect.getWalletInfo()` and it will throw an error if no user is logged in.
