### ISSUE TITLE
How is private key generated when using magic connect?

### ISSUE THREAD

**Issue by haowang1013** [magiclabs/magic-js#385]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I want to understand how the private keys are generated for new users login with email.
It is mentioned that the private key is generated client side within the iframe then uploaded to magic's backend for storage but I can't seem to find the corresponding logic in this repo. Can you please point me to the code where this is implemented?

Note that I found this [getPublicKey](https://github.com/magiclabs/magic-js/blob/master/packages/%40magic-sdk/provider/src/util/web-crypto.ts#L63) function but I don't think it's related to the wallet creation, is it?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser          |
| `yarn`           |
| Operating System |

**Comment by ayv8er** [comment]
Please refer to our whitepaper which explains our Delegated Key Management system.

1. Navigate to https://magic.link
2. Hover over 'Resources'
3. Click on 'Whitepaper'

**Comment by haowang1013** [comment]
> Please refer to our whitepaper which explains our Delegated Key Management system.
> 
> 
> 
> 1. Navigate to https://magic.link
> 
> 2. Hover over 'Resources'
> 
> 3. Click on 'Whitepaper'

Thanks, I did went through the white paper and understood the basic idea but I'm having a hard time finding how it's implemented in this repo, which is why I asked about it.
