### ISSUE TITLE
Intermittent log outs on desktop Chrome + Safari

### ISSUE THREAD

**Issue by pkayfire** [magiclabs/magic-js#392]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Our users are experiencing intermittent logouts on desktop Chrome + Safari even after the fix for issue https://github.com/magiclabs/magic-js/issues/279. We believe there is still a session persistence issue on desktop browsers.

### 🧩 Steps to Reproduce

1. Login using Magic
2. Wait a random amount of time (usually a couple days)
3. User is brought to logged out page even though they didn't explicitly log out

### 🤔 Expected behavior

User is logged in for the duration of the session. We currently have sessions set to 90 days and to auto-refresh using the Magic dashboard.

### 😮 Actual behavior

User is only logged in for a couple days before being logged out.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 10.0.0
| Browser          | Google Chrome 107.0.5304.110 and Safari 15.4
| `yarn`           |
| Operating System | MacOS 12.3

**Comment by pkayfire** [comment]
cc @mikeavvad who was also facing this issue

**Comment by ayv8er** [comment]
@pkayfire The steps to reproduce require some time to test this. Please allow for a few days for me to reproduce and update.

**Comment by mikeavvad** [comment]
@ayv8er  @Ethella I have quite a similar issue, let me describe it.

So for me Chrome is ok (at least for 2-days short session), but in Safari and Brave Magic drops the session after a couple of refreshes (less than 1 minute). 
Is it a separate bug and I should create another issue?

**Comment by stepheljobs** [comment]
oh jeeez! ive been fixing this issue for 2 days already, glad ive checkd the repo.. i have the same issue with brave browser.

**Comment by pkayfire** [comment]
I'm having the Magic team investigating it now. They've been trying to replicate the issue on our app on desktop Safari + Chrome (macOS). I'll keep everyone updated.

**Comment by ayv8er** [comment]
Hi everyone, I am trying to reproduce this myself because no one has been able to provide steps that result in reproducing this.
@pkayfire, I have been monitoring sessions on both Chrome and Safari on your app for 9 days now. I will continue for as long as possible. If you have any additional information you can provide, I'd highly appreciate it.

**Comment by ayv8er** [comment]
@stepheljobs The issue with Brave is that the app will not detect session in Brave when shields are enabled. Please disable shields, it will solve the issue.

If you require shields to be enabled, please try going to brave://settings/cookies, scroll down and under Sites that can always use cookies, try adding:

- [*.]magic.link (check including third-party cookies on this site)

Scroll way down to the bottom, make sure that neither magic.link or csb.app is included under:

- sites that clear cookies when you close them
- sites that can never use cookies

**Comment by stepheljobs** [comment]
Thank you @ayv8er !

**Comment by mikeavvad** [comment]
@ayv8er thanks for your answer regarding Brave! But what about Safari? Seems like it acts just like Brave for me.

**Comment by pkayfire** [comment]
Closing for now as Magic team were unable to reproduce and we haven't had any users reporting the issue recently.
