### ISSUE TITLE
Encryption and decryption using the user's private key

### ISSUE THREAD

**Issue by hamzatrq** [magiclabs/magic-js#408]
### ✅ Prerequisites

- [ ✅] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [ ✅] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Magic SDK do not allow accessing user's private key which is a good thing. But the provider is limited to signing only. It must also have functions for encrypting and decrypting the data. Just like signing it.

## 🧩 Context

One of the biggest requirement for the app that I am working on, is to be able to encrypt user generated data and then decrypt it when needs by the same user. The data gets stored in the database but users can trust that their data is secure and even if someday some hacker hacks into the system he will still not be able to access the data.

## 💻 Examples

A privacy focused To Do app.

1. User logs in using Magic Link Auth
2. User inputs a text string into the app
3. App calls the encrypt function which uses the user's public key to perform ECIES encryption
4. Encrypted data gets stored in a centralised server
5. User logs out
6. User logs in through his phone
7. App fetches the data from centralised server
8. App calls the decrypt function using the user's private key to decrypt the encrypted data

**Comment by hamzatrq** [comment]
Still waiting for a response @kgrubb

**Comment by jdnichollsc** [comment]
is there any plan to support exporting the private key or supporting partial signatures as well?

**Comment by trisha** [comment]
Interested in this as well

**Comment by hamzatrq** [comment]
Exporting the keys will compromise the security of magiclink. We moved ahead with web3auth. But their solution is not ready for production. 
If there could be a way to add custom functionality to the provider or maybe an option to create extensions (along with documentation). Magic link becomes a great authentication solution.

**Comment by hamzatrq** [comment]
Thank you @jdnichollsc. The feature took so long that by now we already moved ahead with Web3Auth enterprise plan. But it looks promising. Looking forward to using it in future!
