### ISSUE TITLE
what is the path used to generate wallet from mnemonic ?

### ISSUE THREAD

**Issue by garyng2000** [magiclabs/magic-js#410]
there is an option to 'reveal mnemonic' when I tested out an app say at some acme.com site. when I use that feature, I have to login to auth.magic.link which shows me a completely different address after login(same email address).

and after I download the mnemonic, I try to use the standard PATH and get yet another address. so how can I recover my ownership if anything happens ?

**Comment by ayv8er** [comment]
For Magic Auth apps, end users are able to reveal their secret phrase through a reveal site which is created and maintained by Magic, and not the app owner. If the app in question is using the same Magic publishable API key that is also used to create that reveal site, an end user from said app will be able to export their secret phrase.

**Comment by garyng2000** [comment]
I am referring it as the 'end user'. So I see/export the mnemonic but it is sort of useless for me as without knowing the path use for 'site A'(that use magic with some api key), I cannot generate my wallet address. So if say 'site A' goes out of business, all things tied to that I can no longer control. How would you recommend the 'end user' to solve it in this situation ?

**Comment by ayv8er** [comment]
This is in regards to the Magic Auth product.

The situation for the end user would largely depend on IF and HOW 'site A' allows their end users to get their secret phrase.
Assuming the app owner allows this, Magic would have created a reveal site for the application and provided the URL to the app owner.
Magic would have no way of informing the end users of this reveal page, so how and when the app owner provides this to their end users would be an important factor.

If the app owner notifies all their end users of this reveal page and 'site A' goes down, the end users will continue to have access to the reveal page, unless the app owner has intentionally deleted/closed the app.

**Comment by garyng2000** [comment]
Base on what I see, the site is only using the Magic Connect(basically in browser wallet, well but somehow managed by magic). Do you mean if I am the developer of the site, I have to do something(in the code or the dev portal) such that I can provide an option to the end user to say 'visit this url if you want to 'backup'/'download' your wallet private key/mnemonic ? The point I am confused is that the standard magic ux(used by the app) does have an option to 'reveal mnemonic' but it brings me to another site 'auth.magic.link' which shows a totally different wallet address(from site A) and even I get the mnemonic, I still don't know what the path(m/164... or whatever) is used to generate the secret key for site A. I just need to know a way for 'site A'(as a developer) to tell the user 'no worry, you still in control of your keys if anything happens. just go to XXX and login with your email/gmail and you get the private key'

**Comment by am-hernandez** [comment]
@garyng2000 thank you for opening this issue and asking this question. The wallet follows the BIP44 standard, the derivation path is `m/44'/60'/0'/0/0`.

**Comment by garyng2000** [comment]
there must be something else that is hidden. I use magic connect. the address shown is different if I tried to connect to auth.magic.link(where I can reveal the mnemonic). I feed that mnemonic into ethers js and tried all possible path(m/44'/60'/0'/0/{whatever}) and never get either the address in the app or the address under auth.magic.link, even though the login email is correct

**Comment by am-hernandez** [comment]
@garyng2000 I passed the mnemonic I got from **Magic Connect** into `ethers.js` and got the same public address I see in **Magic Connect**. Here's what I did:

```javascript
> const { ethers } = require("ethers");

> const wallet = ethers.Wallet.fromMnemonic(process.env.MNEMONIC);

> console.log(wallet);

Wallet {
  _isSigner: true,
  _signingKey: [Function (anonymous)],
  address: '0xF3..................................afb1',
  _mnemonic: [Function (anonymous)],
  provider: null
}
```

I did not need to pass in the derivation path because if it is left out `ethers.js` will use the default path that I provided. The result will be the same with the path added as an argument when calling `ethers.Wallet.fromMnemonic(process.env.MNEMONIC, "m/44'/60'/0'/0/0")`.

**Comment by garyng2000** [comment]
yes, and that puzzle me. I can get the address that is in the auth.magic.link site(where the mnemonic is revealed) but not the same as my app.

**Comment by am-hernandez** [comment]
@garyng2000 we answered the question for this issue so I will keep this one closed. Please open a new issue for the behavior you are experiencing where you see a different public address in your app versus wallet.magic.link. We can continue in the new issue you post. 

Alternatively, you can bring this to our [helpdesk](https://magic.crisp.help/en/) and receive **1:1** live support.

Thanks again!
