### ISSUE TITLE
use custom rpc node

### ISSUE THREAD

**Issue by garyng2000** [magiclabs/magic-js#411]
I followed the example to to use custom rpc node(for my own internal testing network) but it simply cannot load the magic link(which I think is in in iFrame) because of the CSP where magic.link depends a known list of domain and obviously mine is not included. I tried to find the place in the dashboard to see if there is any place to change this but failed.

So how exactly am I supposed to use my own domain for the rpc node ?

**Comment by ayv8er** [comment]
Hello @garyng2000, at the current moment you would only be able to use custom rpc nodes that utilize a whitelisted domain on our end. If you need a domain whitelisted, please reach out to us at support@magic.link with the domain and other pertinent information so we can evaluate adding it to our whitelist. Thank you

**Comment by garyng2000** [comment]
I have used a local proxy(localhost:8545 proxying to the actual node, as I only do it for testing/dev) and get passed the CSP part but still it doesn't work. the dialog popup but those login option doesn't(the email box etc.) it is as if something is not loaded. though I do see my node being queried for chainId. I started to give up the idea of using this,
