### ISSUE TITLE
[Iphone 14 SafeAreaView issue | Cross button not clickable  - React Native]

### ISSUE THREAD

**Issue by adeelcheeema** [magiclabs/magic-js#422]
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-05 at 11 08 47](https://user-images.githubusercontent.com/36962178/210713984-f0c0a72e-cebd-4379-b174-c69c2962e305.png)

With Iphone14 the cross button is not clickable as it is under the status bar.

**Comment by ayv8er** [comment]
Hello @adeelcheeema, can you confirm you are wrapping the relayer in the SafeAreaProvider?

**Comment by adeelcheeema** [comment]
Yes , the layer is wrapped inside SafeAreaProvider.

**Comment by asooge** [comment]
+1 similar issue on iphone 13 using react and capacitor. Is there any way to customize the modal style to avoid this?

**Comment by Ethella** [comment]
Thx for reporting this. Taking a look now

**Comment by Ariflo** [comment]
@adeelcheeema This issue will be resolved when this PR is merged. https://github.com/magiclabs/magic-js/pull/431

**Comment by magiclabsFE** [comment]
:rocket: Issue was released in [`@magic-ext/react-native-bare-oauth@8.0.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-bare-oauth%408.0.0), [`@magic-ext/react-native-expo-oauth@8.0.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-expo-oauth%408.0.0), [`@magic-sdk/react-native-bare@14.0.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-bare%4014.0.0), [`@magic-sdk/react-native-expo@14.0.0`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/react-native-expo%4014.0.0) :rocket:
