### ISSUE TITLE
Support localhost evm for local development

### ISSUE THREAD

**Issue by ingig** [magiclabs/magic-js#428]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request
The following request applies to Magic Connect

When running on hardhat/truffle instance of EVM pointing to localhost (chainId: 31337), the login does not work. That is because localhost is not defined in the available networks
![image](https://user-images.githubusercontent.com/103004/210999981-a57f8136-c662-489c-b343-ab7445d04ee7.png)

## 🧩 Context

When developing on localhost, it's not possible to login, but the workaround is to connect to different supported chain in the wallet, login using that chain, then switch back to localhost. 

Makes development easier, also library gives Javascript error if the chain is not supported, might be good to fix that

![image](https://user-images.githubusercontent.com/103004/211000370-d29e7d9f-c441-468c-90ab-b8df40328652.png)

**Comment by ayv8er** [comment]
@ingig, you can add localhost for EVM development by adding domain(s) to the Content Security Policy section of your application's setting. If you want to add multiple, please separate each URL with a comma.
![Screenshot 2023-10-16 at 4 58 19 PM](https://github.com/magiclabs/magic-js/assets/84942969/eff03cc5-0822-414c-a198-89bb2a16094f)
