### ISSUE TITLE
address/private key use is different between app and auth.magic.link

### ISSUE THREAD

**Issue by garyng2000** [magiclabs/magic-js#430]
we are developing app using magic.link connect(not auth). In order to give use the peace of mind, we have to test out the 'reveal my mnemonic' feature.

what I have found is after login to auth.magic.link(that is the only site that can reveal mnemonic), I see a completely different address shown. after download the mnemonic and put it in ethers js, I can get the same address as shown in the auth.magic.link site BUT that is obviously different from within our app. So without a way to generate the private key for what the app is using, there is no backup for the user and if our app is gone, whatever belong to that addresses would be locked forever.

what can be the possible cause for this ?

**Comment by ayv8er** [comment]
There are 2 products; Magic Connect and Magic Auth.

Magic Connect apps has the reveal phrase function built into the wallet UI.
Please note a user on a Magic Connect app will have the same wallet across all Magic Connect apps.

I don't understand what you mean by "login to auth.magic.link(that is the only site that can reveal mnemonic)"

Logging into any Magic Auth app with the same credentials as you used for the Magic Connect app, will NOT return the same wallet address. 
A user on a Magic Auth app will only have access to that wallet on that single app because users are tied to that app's publishable API key.

If you believe I am misunderstanding you, please reach out to the chat widget on our home page for a deeper discussion.
https://magic.link/

**Comment by garyng2000** [comment]
well I just follow the standard UI of 'wallet connect'(that top left button) which has a 'wallet secret phase' option but when I click it, it said I have to login to another app(which is the auth.magic.link site) and that is where I get the phrase but the address between these two are different. see attached
![image](https://user-images.githubusercontent.com/241666/211884406-8a0be801-d236-4a52-876d-8d249ad475ea.png)

**Comment by am-hernandez** [comment]
Hi @garyng2000 , thank you for opening this new issue!

Would you please try logging into https://wallet.magic.link/?network=goerli, where the network is set to Goerli? You should see the same address there as you are seeing in your app. Please let us know if that's what you observe.

Judging from the screenshots you shared in the previous comment, I see that you are testing on `Goerli` and logging into the wallet through Magic's Wallet site on Ethereum mainnet.
Your wallet address will be consistent across all networks except for `Goerli`.  This difference only occurs when setting `network: 'goerli'` when instantiating Magic as shown below:

```javascript
const magic = new Magic('YOUR_API_KEY', { 
  network: 'goerli',
  extensions: [new ConnectExtension()]
});
```

You may use your own custom Ethereum Goerli node to ensure you see the same wallet addresses when connected to either network.

```javascript
const magic = new Magic('YOUR_API_KEY', { 
  network: 'custom_goerli_node_url',
  extensions: [new ConnectExtension()]
});
```

**Comment by garyng2000** [comment]
yes, indeed it seems to be related to goerli, if I switch to mainnet, I can see the same address. though I have tried to use custom url before but unfortunately, that only works for 'selected domains(only infura/alchemy etc.)' due to your apps security policy(in the iframe). But so long there is a way to retrieve the wallet key, it is fine it is only goerli that is the issue. thanks for they help. though I suggest have it document  some where

**Comment by am-hernandez** [comment]
@garyng2000 I agree, we should and will addd wording about this to the docs. Thanks for following up!
