### ISSUE TITLE
Session persistence doesn't work with NextJS

### ISSUE THREAD

**Issue by BriungRi** [magiclabs/magic-js#442]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Using `magic-sdk` with NextJS works for login and signup. However, session persistence doesn't seem to work out of the box.

### 🧩 Steps to Reproduce

1. Visit the official NextJS demo [post](https://magic.link/posts/magic-link-nextjs) [demo](https://magic-nextjs.vercel.app/login)
2. Login
3. Refresh the page

### 🤔 Expected behavior

After logging in, I would expect to remain logged in after refreshing the page.

### 😮 Actual behavior

After logging in and refreshing, I am prompted to log in again.

### 💻 Code Sample

https://github.com/magiclabs/example-nextjs

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 13.1.0
| Browser          | Brave v1.47.171
| `yarn`           | 1.22.19
| Operating System | `macOS`

**Comment by ayv8er** [comment]
@BriungRi 
Could you try logging into this demo app, on Brave.
After you login, refresh, and you should reroute to the login page per this issue.
Then try to disable Brave Shields.
Does it immediately log you back in?

**Comment by BriungRi** [comment]
Wow, you're right. I turned off `Block cookies` and persistence worked. I guess this isn't NextJS specific then. Will this issue even fixable?

![Screenshot 2023-01-27 at 2 46 29 PM](https://user-images.githubusercontent.com/8957844/215183278-d3e03602-0c19-43ea-adfb-77b88071e33a.png)

**Comment by ayv8er** [comment]
Brave's Shields are incredibly effective... 
Our Magic Auth Plus subscription offers DPoP custom session persistence which could increase the scenarios where the session persists for users.
