### ISSUE TITLE
 React-Native iOS app rejected(Guideline 4.0 - Design) on AppStore for using @magic-sdk/react-native

### ISSUE THREAD

**Issue by raviranjan31** [magiclabs/magic-js#444]
### ✅ Prerequisites

- [yes] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [yes] Are you running the latest SDK version?
- [yes] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
IOS app rejected by AppStore with "Guideline 4.0 - Design"

Rejection Reason provided by app store:

Guideline 4.0 - Design
We noticed that the user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.
Next Steps
To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.
You may also choose to implement the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

### 🧩 Steps to Reproduce

Publishing App to AppStore

### 🤔 Expected behavior

[What you expected to happen?]

### 😮 Actual behavior

[What actually happened? Please include any error stack traces you encounter.]

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser          |
| `yarn`           |
| Operating System |

**Comment by ayv8er** [comment]
@raviranjan31 Thank you for bringing this to our attention.
Our team will look into this and we may reach out for more information.

**Comment by ayv8er** [comment]
@raviranjan31 Would you mind confirming your implementation? Are you using `@magic-sdk/react-native` or `magic-sdk`?

**Comment by ashishmadan** [comment]
"@magic-sdk/react-native": "^8.1.0",

**Comment by Ariflo** [comment]
> We noticed that the user is taken to the default web browser to sign in or register for an account, which provides a poor user experience.

Hi @ashishmadan can you clarify the UX here? Are your users being taken out of the app context and sent to a safari mobile browsing context to sign in? 

If you haven't done so already, I'd also like to encourage you to review our [sample RN apps](https://github.com/magiclabs/react-native-demo). Have you and your team considered switching to using our latest split package for bare RN setups?

**Comment by raviranjan31** [comment]
Hi @Ariflo ,

I have attempted to resolve the issue by implementing the new split package, but unfortunately, app has been rejected by the App Store due to non-compliance with guideline 4.
The reason cited was the usage of webview, which needs to be shown through the Safari view with the URL and its certificate so user know where they are inputing their email id. 

I wanted to bring to your attention that this issue has also been faced by the Auth0 Library, as referenced in the following community post: https://community.auth0.com/t/react-native-ios-app-rejected-on-appstore-for-using-react-native-auth0/36793

Thank you for your time and consideration. I am looking forward to your response.

**Comment by Ariflo** [comment]
Hi @raviranjan31, I'm very sorry to hear this is happening to you. To help you troubleshoot further, can you confirm which of our login features you've integrated into your app? Given the above Auth0 Library example, can we assume you're trying to use  social login?

**Comment by raviranjan31** [comment]
We are not doing social login and they complaining about attached screen and asking us to show url/certificate so user know where they are entering email id.
 
![simulator_screenshot_C63BED0A-B1CA-445B-9663-6CBD03BF5F00](https://user-images.githubusercontent.com/98770719/216492739-32efd5e3-d69a-4fc4-b55a-1ff7f5ab733a.png)

**Comment by Ariflo** [comment]
Got it @raviranjan31, Thanks for clarifying. We'll work on getting something out asap.

**Comment by Ariflo** [comment]
@raviranjan31, we are going to do what we can to get `loginWithLink` to work within Apple's guidelines. Thank you again for bringing this to our attention.

In the meantime,  if you need to get through the review process, we think it might help to integrate [social login](https://magic.link/docs/auth/login-methods/social-logins/integration/oauth-implementation/react-native) in place of `loginWithLink`; as it utilizes Apple's `AuthSession` instead of the Webview.

**Comment by Ariflo** [comment]
@raviranjan31 any updates on using social login? Assuming that's not an option:

>which needs to be shown through the Safari view with the URL and its certificate so user know where they are inputing their email id.
>![](https://user-images.githubusercontent.com/98770719/216493338-a00145b8-d65a-49ec-a939-19d4f6f43b87.png)


Could reach back out to Apple and inform them that although the `WebView` displays an edit button here, tapping it ultimately brings the user back to the app where they actually input their email? In other words, your app is the entity that collects the information and ergo forwards it along to us for wallet services. The user never inputs their email directly into our SDK's WebView.

**Comment by AMAN-BARBARIA** [comment]
We have implemented MagicAuth `loginWithEmailOtp` functionality for our mobile app. We have been working on it since last week and were planning to release it early next week. But after seeing this thread, I want to confirm if this issue is fixed as per apple's guideline. 
What I do not want is to release the feature in testflight for people to sign up and later remove their login in app store. If you guys suggest to go with `Social Logins`, we will start implementing it.

**Comment by Ariflo** [comment]
Hi @AMAN-BARBARIA unfortunately we haven't heard back from @raviranjan31. As we note above we believe `loginWithEmailOtp` along with the rest of our product line should pass the review process. Reach out to us here if you experience otherwise.

**Comment by AMAN-BARBARIA** [comment]
> Hi @AMAN-BARBARIA unfortunately we haven't heard back from @raviranjan31. As we note above we believe `loginWithEmailOtp` along with the rest of our product line should pass the review process. Reach out to us here if you experience otherwise.

Hi @Ariflo, are there other apps using `loginWithEmailOtp` that got through the apple review process in the last month? 
Want to be double sure, before deciding to proceed with `loginWithEmailOtp`

**Comment by Ariflo** [comment]
> there other apps using loginWithEmailOtp that got through the apple review process in the last month?

Yes, you should proceed with confidence. We haven't seen this issue crop up more than once. Although, I can't promise anything as things are constantly changing with Apple's review process. Please do let us know if you run into issues.

**Comment by betashop** [comment]
Hi @Ariflo 

I chatted with Richard from your team at ETH Denver yesterday and he said there was some customizations being worked on that would help with this issue. Can you share any more details? He said we should be able to make it more appear that the screen is being served up by the app itself.

Also, can you provide some examples of customer apps in the app store that are using Magic.Link that we can download and reference?

Thanks!

**Comment by Ariflo** [comment]
@betashop I can't share the details on the customization being worked on, as it is still in development. But I'll reiterate, that besides this particular GH issue, we haven't seen this problem crop up with any other developers. 

[HeartBeat App](https://www.heartbeat.chat) and [Snowball](https://apps.apple.com/us/app/snowball-smart-defi-wallet/id1449662311) are two examples of apps on the App Store using Magic link.

**Comment by ayv8er** [comment]
@betashop 
Hi again, I was referring to [this feature in our docs](https://magic.link/docs/auth/api-reference/client-side-sdks/web#loginwithmagiclink).

If you pass `showUI = false` into `loginWithMagicLink`, you can render your own modal informing the end user to check their inbox, instead of seeing Magic's branded modal.
Our popup modal that appears after the user submits their email address is web view. But if you created your own modal you wouldn't render a web view to the end user.

We are working on having this available for the other email login method `loginWithEmailOTP`. It is currently in development.

> We are not doing social login, we are using loginwithlink and they complaining about attached screen and asking us to show url/certificate so user know where they are entering email id. app store is saying to not use web view and use safari view for this with url and certificate should present in header.
> 
> ![image](https://user-images.githubusercontent.com/98770719/216493338-a00145b8-d65a-49ec-a939-19d4f6f43b87.png)
