### ISSUE TITLE
Web3 integration - after logging out on Magic modal, is there any callback so that I can run another logout actions on dapp?

### ISSUE THREAD

**Issue by swdreams** [magiclabs/magic-js#447]
### ✅ Prerequisites

- [No ] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [ Yes] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I want to integrate your magic link on my dapp:  https://ds-staging-mainnet.vercel.app/
I use web3 and followed your documentation and everything works correctly.
But I have a big problem on logout.
After logging out on your magic dialog, I need to catch any callback because my dapp has its own logout logic and I need to run a function to log out a connected wallet from the app.

Steps:
1. Login to Magic. A wallet has been connected correctly. I can run any web3 action.
2. I open the magic wallet dialog by `showWallet()`
3. And I logout on magic.
4. Logout seems correct. But I need to catch the point when a wallet has been logged out from magic because I need to run the app's logout process.
But magic logout has been done in background and I  can't get the magic's logout callback.

Is there any event for it?

### 🌎 Environment

Reactjs: 17.0.1

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |13.1.0
| Browser          | Chrome v109 64bit
| `yarn`           |
| Operating System | Vercel server or local windows 11

**Comment by ayv8er** [comment]
@swdreams We don't have events you could catch on the logout. We would have to add that as a feature request. Could I ask more specifically about your use case? The logout would disconnect the Magic user, what else are you doing on your end to disconnect from your app?

**Comment by swdreams** [comment]
@ayv8er Thanks for your quick answer. 
Normally, web3.js allows developers to subscribe events: `disconnect`, `accountsChanged`, `chainChanged` via prcprovider so that we can get the wallet change and apply it to the biz logic accordingly.

But your magic's logout doesn't emit `disconnect` event  at all. So this is not compatible with the other connectors such as Metamask, coinbase, WalletConnect, etc.

So I feel that we can't use your great feature for now.

If this can be done shortly, it would be perfect.  If possible, please let me know your plan or decision as well.

Looking forward to hearing from you soon.

**Comment by ayv8er** [comment]
@swdreams You can now subscribe to a `disconnect` event after the user renders the Magic Connect wallet modal and disconnects from it.
https://magic.link/docs/connect/wallet-api-reference/javascript-client-sdk#showui()
