### ISSUE TITLE
Expose API to allow MagicAuth users export wallet

### ISSUE THREAD

**Issue by tylerpashigian** [magiclabs/magic-js#467]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

In MagicConnect, the modal allows the functionality for users to export their private keys in order to import the wallet to a non-custodial wallet. In order to get access to this functionality while using MagicAuth, you have to [request the MagicLink team](https://magic.link/docs/auth/introduction/faq#how-can-i-allow-users-to-view-and-export-their-private-key) expose a dynamic web page allowing users to do this. Since this functionality already exists it would be great if there is an API that allows developers create an in-app experience to do this.

## 🧩 Context

Having users navigate to a randomly generated page with a host that doesn't match the host of our app could raise some security concerns. I spoke with someone at ETH Denver about this at the Magic booth and they suggested I raise a feature request here.

**Comment by carrie-hk** [comment]
I would greatly appreciate this feature.

**Comment by jdnichollsc** [comment]
With my team we need this instead of exposing the Private key as I requested here: https://github.com/magiclabs/magic-js/issues/532

Any plans to support this feature? Please let us know! <3

**Comment by joshuascan** [comment]
Hi everyone. I will bring this up to our product team and will follow up here. Thanks!

**Comment by joshuascan** [comment]
Hi again. Thanks for your patience. I brought this up to our team, and while it is something we are interested it, we will not be pursuing it in the immediate future. Thank you for the request though!
