### ISSUE TITLE
Request Zh-Cn localization for email reply template 

### ISSUE THREAD

**Issue by JianhaoLuo18** [magiclabs/magic-js#468]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

`Magic(magicLinkPK, {locale: 'zh_CN'});`

I see that we have localization for zh-Cn, but it's not complete yet!
the email reply template is still in English. See below screenshots

## 🧩 Context
https://ibb.co/2sVB1Wx
https://ibb.co/zSwq398
[Explain any additional context or rationale for this feature. What are you trying to accomplish?]

## 💻 Examples

[Do you have any example(s) for the requested feature? If so, describe/demonstrate your example(s) here.]

**Comment by joshuascan** [comment]
Hi @JianhaoLuo18. I have elevated this to our engineering team and will follow up with any updates. Thanks!
