### ISSUE TITLE
Blank Screen on webview for android devices when using `GoogleLogin` or `AppleLogIn`

### ISSUE THREAD

**Issue by dakshbhardwaj** [magiclabs/magic-js#472]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
For some android devices after `OAuth` with `Google` or `Apple`, the webView remains on the `auth.magic.link`  webpage without any loader and even after waiting for a long time it doesn't redirect to the application.

The same code is working fine for iOS devices and some android devices.

### 🤔 Expected behaviour
It should show the loader, and error and redirect to the application.

### 😮 Actual behaviour

https://user-images.githubusercontent.com/22423684/224284916-69650a87-e7e7-44d9-ad19-24613e26a0d7.mp4

### 💻 Code Sample

We have called the following methods for showing the Login Popup for google and apple.
``` 
MagicLink.oauth
        .loginWithPopup({
          provider: 'google',
          showUI: true,
          redirectURI: 'uri_of_our_app',
        })
        
```

### 🌎 Environment

Device Details 
Device: Oneplus Nord2
Android Version: 12

| Software         | Version(s) |
| ---------------- | ---------- |
| `@magic-ext/react-native-bare-oauth` | 8.6.0
| `@magic-sdk/react-native-bare` | 14.4.0 
| `"react-native-inappbrowser-reborn` |  "3.7.0",`

**Comment by Ariflo** [comment]
Hi @betashop, we'll take a look and report back. Thank you for bringing this to our attention.

**Comment by Ariflo** [comment]
@dakshbhardwaj @betashop could you reach out to our customer support so that we can officially get this issue in our system? In particular, please share your `uri_of_our_app` with our rep. Thanks!

**Comment by ayv8er** [comment]
@betashop 
Customer support is here, we'll create a ticket and queue this one for investigation.
We'll reach back out if we have any questions or updates.

**Comment by betashop** [comment]
Here is our uri_of_our_app
https://auth.magic.link/v1/oauth2/kft1uuWwQofmp3i4mNRVBx2XAob9oVATTrnY5IT1Mng=/callback

I have checked just now with "Test Connection" and it is working with the web, but in Android.

**Comment by Ariflo** [comment]
@betashop apologies for the confusion, but our mobile SDKs are expecting an `app scheme` (ie `app name://` in the `redirectURI` parameter. Try directly passing it as a `string` and let us know if you continue to run into this issue.

**Comment by betashop** [comment]
Thanks. @dakshbhardwaj will check in the am (he's in India) and let us know. 

Appreciate the help!

**Comment by dakshbhardwaj** [comment]
Hi @Ariflo yes we are already providing an `app scheme` in `redirectURI` parameter. Below is the code snippet for the same 
```
MagicLink.oauth
        .loginWithPopup({
          provider: 'google',
          showUI: true,
          redirectURI: 'Jam-Staging://jam',
        })
    ```

**Comment by dakshbhardwaj** [comment]
Hi @Ariflo we tried to do the `googleLogIn` in the sample app (https://github.com/magiclabs/react-native-demo/tree/main/bare) and the experience was the same, the loader keeps loading after authenticating the email.

https://user-images.githubusercontent.com/22423684/224468706-61b80c5c-8234-4435-9295-f83e1dc156bb.mov

**Comment by betashop** [comment]
@ayv8er @Ariflo just escalating the above, please let us know as our launch is Tuesday. Thanks.

**Comment by Ariflo** [comment]
Thanks @betashop @dakshbhardwaj, we're taking a look.

**Comment by Ariflo** [comment]
@betashop @dakshbhardwaj Upon further investigation, this looks to be a known issue with [react-native-inappbrowser-reborn ](https://github.com/proyecto26/react-native-inappbrowser). That said, we're going to do what we can on our end to get this patched or find a replacement for the module.

In the meantime, given your tight timeline, we recommend you utilize React's [Platform](https://reactnative.dev/docs/platform) Module to detect Android devices and pass an  [App Link](https://developer.android.com/training/app-links#android-app-links) as the `redirectURI` to our API instead. We've found that `https` based links seem to work better than `deepLinks` in this case.

**Comment by dakshbhardwaj** [comment]
Thanks, @Ariflo we tried with the `https` based link but it's not redirecting to that link, it stays on the `auth.magic.link` with the same behaviour as seen in the video above.

**Comment by Ariflo** [comment]
@dakshbhardwaj That is odd, could you try passing `https://google.com`  to the `RedirectURI` and tell us what you experience?

**Comment by ayv8er** [comment]
@betashop Would you be able to hop on a chat with us on our homepage so I can get more info from you?
There's a chat widget at the bottom right corner of our home page; https://magic.link/

**Comment by Ariflo** [comment]
@dakshbhardwaj  @betashop Just want to reiterate that the problem here is with [react-native-inappbrowser-reborn ](https://github.com/proyecto26/react-native-inappbrowser) and we are working to find a secure replacement asap. For what it's worth, the problem is that it utilizes `startActivity` as opposed to `startActivityForResult` to handle the redirect on Android. 

That said, in the meantime, have you considered using any of our other product offerings like [loginWithEmailOTP](https://magic.link/docs/auth/api-reference/client-side-sdks/web#loginwithemailotp) or [loginWithSMS](https://magic.link/docs/auth/login-methods/sms/integration/react-native) for your Android app?  

We know this answer is not ideal, but we will need time to find a viable replacement to `react-native-inappbrowser-reborn`.

**Comment by dakshbhardwaj** [comment]
Hi @Ariflo @ayv8er upon further investigation, this looks like it is a device-specific issue. we have tested it on other android devices and it's working fine.

Device details for which it's not working is 

Device Details
Device: Oneplus Nord2
Android Version: 12

**Comment by dakshbhardwaj** [comment]
We faced the issue again on `iPhone 13` `5-6` hrs ago the loader was not appearing and even after waiting for a long time and it doesn't redirect to the application.  

All of a sudden it again started working normally.

**Comment by betashop** [comment]
Hi @Ariflo this is not an acceptable answer. We are paying Magic.Link for social logins.

>That said, in the meantime, have you considered using any of our other product offerings like [loginWithEmailOTP](https://magic.link/docs/auth/api-reference/client-side-sdks/web#loginwithemailotp) or [loginWithSMS](https://magic.link/docs/auth/login-methods/sms/integration/react-native) for your Android app?

**Comment by Ariflo** [comment]
@betashop we are working on an update to the extension. Please reach out to @ayv8er on our support staff via chat who will gather the information we need to verify a solution for you all. Thanks!

**Comment by ayv8er** [comment]
@betashop I'd like to ask for more information that I don't want you to post publicly.
Would you mind starting a chat on our home page at https://magic.link/ and let me know when you do so I can immediately find you?

**Comment by Ariflo** [comment]
@betashop @dakshbhardwaj Not sure if you've already spotted it and apologies for the delay here but it looks like `react-natve-inappbrowser` requires that you [update your React Native app's Android Manifest](https://github.com/proyecto26/react-native-inappbrowser#authentication-flow-using-deep-linking) with the following `intent-filter` to get the redirection to the app post successful login to work:

```
 <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="my-scheme" android:host="my-host" android:pathPrefix="" />
  </intent-filter>
```
