### ISSUE TITLE
Wallet created through Magic SDK vs Fortmatic

### ISSUE THREAD

**Issue by LuwkasLima** [magiclabs/magic-js#475]
### ✅ Prerequisites

- [ x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x ] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I've noticed that if I create a wallet using the same e-mail through Magic SDK (on my DApp) and through Fortmatic/Magic (OpenSea), 2 distinct wallets are created. Does that means each wallet will be exclusively attached to the DApp instead of been 1:1 to the e-mail address?

I was wondering if people minting NFTs on my DApp would be able to trade them on the secondary market places like OpenSea for instance?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser          |
| `yarn`           |
| Operating System |

**Comment by ayv8er** [comment]
@LuwkasLima 
Magic Auth apps are locally scoped to your application's publishable API key.
End users wanting to access the same wallet would need to return to the app of the same Magic Auth publishable API key.

If you're looking for similar behavior in user scope as Fortmatic, consider Magic Connect.
Magic Connect apps are globally scoped like Fortmatic.
One end user can visit multiple Magic Connect applications and will always recall the same wallet.

**Comment by LuwkasLima** [comment]
Thx for the clarification @ayv8er. Happy to know that this is possible, although I see the limitations imposed by the Magic Connect that were not imposed for Magic Auth previously.
