### ISSUE TITLE
magic sdk for web suddenly not working, buffer is not defined

### ISSUE THREAD

**Issue by hilmanski** [magiclabs/magic-js#483]
### ✅ Prerequisites

- [ ✅ ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ ✅ ] Are you running the latest SDK version?
- [ ✅ ] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

We're using Webflow. Not really sure if it's belong here.
Since it's very urgent and support not returning email yet, I'd like to try here since it's for our customers

I found this error on our site.
Which normally worked flawlessly. But after some users complain, we see that an error coming from 
<script src="https://auth.magic.link/sdk"></script>

![Screen Shot 2023-03-27 at 05 41 14](https://user-images.githubusercontent.com/4522467/227953473-6fd0f7ae-abda-4dc7-8729-a98eda434d73.png)

### 🧩 Steps to Reproduce

1. add this <script src="https://auth.magic.link/sdk"></script>
2. 

<script>
  const magic = new Magic('API_KEY');
</script>
```

### 🤔 Expected behavior

no error

### 😮 Actual behavior

no error

### 💻 Code Sample



### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | latest?
| Browser          | all
| `yarn`           | via webflow
| Operating System |

**Comment by fokindmitr** [comment]
Magic sdk installed via npm has the same issue. Both 13.6.2 and 14. Any solutions?

**Comment by am-hernandez** [comment]
@fokindmitr I am using `13.6.2` and am not having an issue. Would you mind sharing more about what you are experiencing? It may deserve its own issue.

**Comment by am-hernandez** [comment]
Closing this issue. We will continue working on the issues with the latest version!
