### ISSUE TITLE
Sepolia testnet is not supported

### ISSUE THREAD

**Issue by zhanleewo** [magiclabs/magic-js#485]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
I setup Magic Connect like this:
```javascript
const sepoliaConfig = { 
    rpcUrl: 'https://eth-sepolia.g.alchemy.com/v2/<API_KEY>',
    chainId: 11155111
};
const magic = new Magic('PUBLISHABLE_API_KEY', {
            network: sepoliaConfig,
            locale: "en_US",
            extensions: [new ConnectExtension()]
        });
```

The Magic SDK throws an exception when I call `connectWithUI`
```javascript
const accounts = await magic.wallet.connectWithUI();
```

Exception Details:
```
TypeError: Cannot read properties of undefined (reading 'chainId')
    at app.chunk~98bac508de36e10a87c8359519285227.50ea9f67fb2971ac6c36.js:1:15082
```

### 🧩 Steps to Reproduce
Simply copy the above code to reproduce

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 14.00
| Browser          | Chrome 111.0.5563.110
| `yarn`           | 1.22.19
| Operating System | macOS Monterey 12.6.3

**Comment by pad01g** [comment]
I could login and send sepolia eth by using infura,io api instead of alchemy.

**Comment by joshuascan** [comment]
Connecting with https://rpc2.sepolia.org/ also works. Please take a look at our [Magic Connect demo](https://codesandbox.io/s/github/magiclabs/magic-demo-react-web3) for further implementation.

**Comment by cbonaco1** [comment]
hey @joshuascan I was facing some issues when using https://rpc2.sepolia.org/ as the rpcUrl in the magic config:
```javascript
new Magic(key, {
    network: {
      rpcUrl: 'https://rpc2.sepolia.org/',
      chainId: 11155111,
    }
  });
```
which I saw in [this example](https://magic.link/docs/universal/getting-started/quickstart#%F0%9F%94%97-connect)
then whenever trying to do anything I see the below error messages:
```
Access to XMLHttpRequest at 'https://rpc2.sepolia.org/' from origin 'https://auth.magic.link' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
also:
```         
POST https://rpc2.sepolia.org/ net::ERR_FAILED 503 (Service Unavailable)
JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)
```
we're using a Dedicated Wallet. below are the versions of relevant packages:
magic-sdk@21.0.0
ethers@6.8.0
next@13.4.7

we got around it by using an Infura URL as the RPC. Please let me know if there is a way to use the sepolia rpc url directly. thanks!
