### ISSUE TITLE
Cannot disconnect from google Magic Connect

### ISSUE THREAD

**Issue by faillacec** [magiclabs/magic-js#495]
### ✅ Prerequisites

- [x ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ ] Are you running the latest SDK version?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

After login google with magic connect, I wanted to logout and connect with other google account but the last session/login never disconnect 

### 🧩 Steps to Reproduce

1. Open Magic connect
2. Connect with a google account
3. Logout
4. Try to connect with magic connect and select another google account
5. Logged to the same account (Last google login)

### 🤔 Expected behavior

1. Open Magic connect
2. Connect with a google account
3. Logout
4. Connect with magic connect and select google account
5. Select google account to connect 
6. Logged

### 😮 Actual behavior

When I logout/disconnect from magic google session, and try to login with another, always keep the same google account, it never logout from the last google account, Cannot select another account to login.

Using disconnect() method to logout as doc says

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 13.4.0
| Browser          | any
| `yarn`           | npm
| Operating System | any

**Comment by ayv8er** [comment]
@faillacec 
If this is reproducible, could you provide a codesandbox or deployed app where we can test this behavior?
