### ISSUE TITLE
Is it magic auth able to send a complete transaction?

### ISSUE THREAD

**Issue by EmanueleBordoni** [magiclabs/magic-js#513]
I opened the following issue [How to set gasPrice for magic connector in Wagmi #78](https://github.com/EveripediaNetwork/wagmi-magic-connector/issues/78) because I'm unable to make a transaction:

```
TransactionExecutionError: An internal error was received.

Request Arguments:
  from:      0xd4B5Bb35...
  to:        0x9302f29960...
  value:     0.01 ETH
  gas:       600000
  gasPrice:  20 gwei

Details: Magic RPC Error: [-32603] Error forwarded from node: insufficient funds for gas * price + value
Version: viem@0.3.24
```

I have a specific question about Magic Auth. Is it able to send a complete payable transaction? I'm using Wagmi (follow the linked issue for more details) and the same transaction works correctly with Metamask.

**Comment by joshuascan** [comment]
Hi @EmanueleBordoni! Magic Auth is able to send a complete payable transaction when used in conjunction with ethers or web3.js. You can see this implementation in [our docs here](https://magic.link/docs/auth/blockchains/ethereum/javascript#send-transaction). I can't speak to it's functionality with Wagmi though as I'm not familiar with using it myself.
