### ISSUE TITLE
Twitter social login is not working anymore

### ISSUE THREAD

**Issue by armanmamyan** [magiclabs/magic-js#514]
### ✅ Seems that starting from the latest releases, Twitter is requiring to have a Bearer token including in request headers.

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
Seems that starting from the latest releases, Twitter is requiring to have a Bearer token including in request headers. And the thing is that it can not be the problem from the project implementation, because you can easily reproduce the issue in the MagicLink dashboard when you are adding Twitter as a social login option, and after filling in the necessary information hitting on the view demo button

### 🧩 Steps to Reproduce

1. Register in [MagicLink](http://magic.link/)
2. Create a Magic Auth app  in your dashboard and open it
3. Click on the social login button in the left sidebar,
4. In the opened menu, choose Twitter 
5. Enable Twitter Sign-in
6. Follow the guide about how to get ClientID and Secret from Twitter
7. Don't forget to copy the Redirect URI and paste it into Twitter 
8. After filling in all necessary information, click on **save** button
9. Click on **View Demo** button on the upper right corner.
10. In the opened window, click on SignIn

### 🤔 Expected behavior

The user should be able to log in to the app via its Twitter

### 😮 Actual behavior
<img width="1786" alt="Screenshot 2023-05-15 at 11 01 28" src="https://github.com/magiclabs/magic-js/assets/30312706/37c6ae37-f501-4ebb-b7d2-4c16e6b3cdbf">

I think that the main problem here is because of the Twitter Bearer token absence in our requests.

**Comment by Sahak1998** [comment]
Same Issue for me

**Comment by vov462** [comment]
bump

**Comment by ayv8er** [comment]
Please try the following.

On Twitter's dev portal, instead of grabbing the info from the OAuth section at the bottom, grab it from the consumer keys section (the API key and secret) and plug those into the Twitter social login section in the Magic dashboard.

![Screenshot 2023-04-28 at 11 36 33 AM](https://github.com/magiclabs/magic-js/assets/84942969/0722a1fa-1ebc-41fd-b37b-3c76dfd3c470)

**Comment by armanmamyan** [comment]
@smithki @Ariflo @bcleary06

**Comment by joshuascan** [comment]
Hi @armanmamyan. Are you still encountering this issue? If so, I would recommend double checking your API keys and implementation. If you take a look at our [deployed demo](https://mpomp0.csb.app/), you can see that our Twitter login is working.
