### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by hickscorp** [magiclabs/magic-js#528]
Our application uses signatures to authenticate our users. Upon clicking an "Authenticate" button, we request the wallet to sign a plaintext known by our backend, and submit it to the backend.
If the signature matches, the user is issued a bearer token allowing them to continue their journey.

Using Metamask, there's a clear confirmation presented to the user. Same goes for any other transaction.
But with Magic, nothing is presented to the user - and Magic simply signs the plaintext without confirmation.

If this is the expected behaviour, then it raises serious security concerns - a malicious page could simply perform a signature request and it would be acknowledged and silently performed by Magic without the user knowledge - thus enabling very easy impersonation attacks on our users.

Will this be mitigated? Or are we wrong in our way of seeing the flow?

**Comment by ayv8er** [comment]
@hickscorp 
Magic allows for various degrees of customization that fits the application's needs.

Advanced applications that desire the behavior you described can give their users a great web2 experience, as long as they understand how to answer the security concerns you've mentioned.

There are several mitigation techniques that Magic provides out-of-the-box, one of which is via the [Wallet SDK (Magic Connect)](https://magic.link/docs/connect/wallet-api-reference/javascript-client-sdk). By making use of this SDK, the following [EVM RPC methods](https://magic.link/docs/connect/wallet-api-reference/javascript-client-sdk#evm-rpc-methods) will always trigger Magic's UI requesting user confirmation.
