### ISSUE TITLE
Is there a way to switch network?

### ISSUE THREAD

**Issue by swdreams** [magiclabs/magic-js#542]
### ✅ Prerequisites

- [ Yes] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [ Yes] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

I am implementing a new feature "Switching network" with Magic & web3js.

I could get it on Metamask wallet by following code:
```
          await (curWeb3.currentProvider as any)?.request({
            method: 'wallet_switchEthereumChain',
            params: [{ chainId: Web3.utils.toHex(newChainId) }],
          })
```

But web3 connected to Magic wallet throws an error. 

Is there any alternative way?

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |17.3.0
| Browser          | Chrome
| `yarn`           | 1.22.17
| Operating System | Windows, CentOS

**Comment by joshuascan** [comment]
Hi. You would want to create magic instances for each of the networks you would like to connect to, and then add the UI functionality to choose which instance of magic you would like to use. [Here is a tutorial](https://magic.link/docs/auth/more/network-switching-tutorial) for an example implementation of this.
