### ISSUE TITLE
Magic RPC Error: [-32603] Internal error: User denied account access.

### ISSUE THREAD

**Issue by undefinedlol** [magiclabs/magic-js#546]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I build a website based on nextjs and use magic link as the wallet solution.it works fine when user sign in with email ,but when connect metamask, when i can `magic.wallet.getInfo`, i got an error `Magic RPC Error: [-32603] Internal error: User denied account access.`

### 🧩 Steps to Reproduce

1. use magic link with metamask

### 🤔 Expected behavior

call `magic.wallet.getInfo` success

### 😮 Actual behavior

failed to call `magic.wallet.getInfo` and get an error `Magic RPC Error: [-32603] Internal error: User denied account access.`

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | ^18.0.0
| Browser          | chrome
| `yarn`           | v1.22.18
| Operating System | mac

**Comment by copostic** [comment]
Same here on a Nuxt 3 project.
We tested with Brave, Chrome ...etc same error only using Metamask.

**Comment by jdnichollsc** [comment]
Hey folks, we're getting the same error with Solana Devnet, do you have any idea about this?

**Comment by ayv8er** [comment]
Thank you for bringing this to our attention, it seems `magic.wallet.getInfo()` is returning the user's metadata, which couldn't be done on users who connect via 3rd party wallets.

We'll look into this and update here as soon as possible.

**Comment by refex** [comment]
Hi, we have this issue too, any update on it?

**Comment by am-hernandez** [comment]
@refex We should have an update by the end of month.

**Comment by ayv8er** [comment]
@puterhimself We're unfortunately not able to get to this today. We will have an update by end of the month.

**Comment by am-hernandez** [comment]
@undefinedlol @refex @puterhimself @jdnichollsc @copostic 

We just pushed out a fix to this issue. When you call `getInfo()` while connected with MetaMask the return value will be the user's wallet type, which in this case would be MetaMask. 


When connected with MetaMask, doing the following

```js
const walletType = await magic.wallet.getInfo();
console.log(walletType);
```

will return: `{"walletType":"metamask"}`

---

Closing this issue as it is now resolved. Please let us know if you believe it is not resolved and we will reopen it. Thank you!

**Comment by devops-prmsnls** [comment]
hey everyone, sorry to keep dragging this on, but we tried this fix and it doesn't work for the BSC network even though its just changing the RPC URL and the chainID, is this intended or a bug? 

please help me out @am-hernandez

**Comment by jdnichollsc** [comment]
@am-hernandez did you try with a Solana Wallet? 😅

**Comment by am-hernandez** [comment]
@devops-prmsnls @jdnichollsc 

This would be a separate issue, which you should feel free to create. 

Magic Connect does not support Solana or BSC, only Ethereum, Optimism, Polygon, and Flow.  You can [find an updated list of supported chains for Magic Connect here](https://magic.link/docs/connect/overview).
