### ISSUE TITLE
Magic RPC Error: [-32603] Internal error: `Your app does not support this method, use an API key from a Magic Auth app instead.`  when clicking on Send button

### ISSUE THREAD

**Issue by MahendraBishnoi29** [magiclabs/magic-js#558]
### ✅ Prerequisites

- [ ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description
I've cloned the demo app from Magic's Official docs and tried implementing Email OTP functionality using Magic's this [Post](https://magic.link/posts/magic-auth-next) but when I click on the send button I get a error in console (I've provided all the necessary ENV variables correctly)
![image](https://github.com/magiclabs/magic-js/assets/74294202/97bfee2d-7099-462a-8b2d-d2f11b82217f)

Error 👇🏻
![image](https://github.com/magiclabs/magic-js/assets/74294202/151db0cd-9978-4c13-af2a-89ae3aebf33f)

### 🧩 Steps to Reproduce

1. Clone [this ](https://github.com/magiclabs/vercel-magic-guide-starter-template) repo and run it locally

### 🤔 Expected behavior

I should get that enter OTP modal and the otp should be successfully sent to my Email like this and Please add a demo with React or Next.js (Codesandbox) because all codesandboxes are for HTML, JavaScript.
![image](https://github.com/magiclabs/magic-js/assets/74294202/c9f47404-dd2f-4008-800c-d88f8639abba)

### 😮 Actual behavior

getting `Your app does not support this method, use an API key from a Magic Auth app instead.` in console

### 💻 Code Sample

**Exact Same Code That is Mentioned [Here](https://magic.link/posts/magic-auth-next)** 

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | ^13.1.0
| Browser          | Chrome
| `yarn`           |
| Operating System |

**Comment by am-hernandez** [comment]
Hi @MahendraBishnoi29 , thank you for posting this issue!

You are getting the error becuase you are using a Magic Connect API key and are calling the login method for a Magic Auth app. The resolution is for you to use a Magic Auth API key. 
 
> ![Screenshot 2023-06-27 at 3 55 03 PM](https://github.com/magiclabs/magic-js/assets/86538622/3b5ee00a-3a41-4ad9-93b0-8f2b17626a23)
> you will want to use the one on the right, Create Magic Auth app

**Comment by MahendraBishnoi29** [comment]
thank you so much @am-hernandez
