### ISSUE TITLE
Can't resolve 'encoding'

### ISSUE THREAD

**Issue by guillermouzner** [magiclabs/magic-js#559]
I have this issue
- warn ./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in 'D:\magic-link\magic\node_modules\node-fetch\lib'     

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/@magic-sdk/admin/dist/esm/utils/fetch.js
./node_modules/@magic-sdk/admin/dist/esm/utils/rest.js
./node_modules/@magic-sdk/admin/dist/esm/modules/users/index.js
./node_modules/@magic-sdk/admin/dist/esm/core/sdk.js
./node_modules/@magic-sdk/admin/dist/esm/index.js
./app/api/login/route.ts

Im usign import nextjs 13.4 with api router.

```bash
import {headers} from "next/headers";
import {Magic} from "@magic-sdk/admin";

import {setLoginSession} from "@/lib/auth";

export async function POST(req: Request, res: Response) {
  const magic = new Magic(process.env.MAGIC_SECRET_KEY);

  const didToken = headers().get("authorization")?.substring(7);

  const metadata = await magic.users.getMetadataByToken(didToken!);

  await setLoginSession(res, metadata);

  return new Response(JSON.stringify({done: true}), {status: 200});
}
```

What should I do?

**Comment by am-hernandez** [comment]
Hi @guillermouzner , thank you for posting this issue.

Would you please let us know which SDK and version you are using and which method call throws this error?

Thank you!

**Comment by guillermouzner** [comment]
Hi!, sure:

```bash
"@magic-sdk/admin": "^1.10.0",
"magic-sdk": "^18.2.0",
```
And got this warning in console:
![image](https://github.com/magiclabs/magic-js/assets/90360692/8d1e6c15-8ed2-40ea-89b9-108b9bfde105)

In app/login/page.tsx i call this method:
```bash
import {Magic} from "magic-sdk";

async function onSubmit(data: FormData) {
  setIsLoading(true)

  const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_API_KEY!);

  const didToken = await magic.auth.loginWithMagicLink({email: data.email.toLowerCase()});

  const res = await fetch("/api/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: "Bearer " + didToken,
    },
    body: JSON.stringify({email: data.email.toLowerCase()}),
  });

  setIsLoading(false)
}
```
And in api/login/route.ts:
```bash
import {headers} from "next/headers";
import {Magic} from "@magic-sdk/admin";

import {setLoginSession} from "@/lib/auth";

export async function POST() {
  const magic = new Magic(process.env.MAGIC_SECRET_KEY);

  const didToken = headers().get("authorization")?.substring(7);

  const metadata = await magic.users.getMetadataByToken(didToken!);

  const token = await setLoginSession(metadata);

  const cookie = serialize("tokenAuth", token, {
    maxAge: 100 * 100 * 100,
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    path: "/",
    sameSite: "lax",
  });

  return new Response(JSON.stringify({done: true}), {
    status: 200,
    headers: {"Set-Cookie": cookie},
  });
}
```

**Comment by am-hernandez** [comment]
Thank you, I see you state you are calling your own function called `onSubmit`, but would you tell me which Magic method call is throwing the error? Is it the Magic instantiation or the login call? 

- `const magic = new Magic(process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_API_KEY!);`
- `const didToken = await magic.auth.loginWithMagicLink({email: data.email.toLowerCase()});`

**Comment by guillermouzner** [comment]
Its in Magic instantiation in api folder
```bash
const magic = new Magic(process.env.MAGIC_SECRET_KEY);
```

**Comment by E0han** [comment]
Hi there, have you solved the problem yet?

**Comment by am-hernandez** [comment]
Hi @guillermouzner  @E0han 

Would you kindly refer to our [Magic + NextJS guide](https://magic.link/posts/magic-auth-next) and let me know if it helps resolves this issue for you? We recently updated that guide so it should help guide you to the resolution, as there may be an error in your implementation. 

Please let us know if it is helpful or not!

**Comment by am-hernandez** [comment]
I am closing this thread now that it is stale. The guide linked in my previous comment should be helpful for anyone else facing a similar issue.

**Comment by sharpsteelsoftware** [comment]
Same issue here -- something going on w/magic and nextjs + vercel

**Comment by guillermouzner** [comment]
Hi @sharpsteelsoftware, I resolved this issue by installing `encoding` as a devDependency.
