### ISSUE TITLE
React Native Deprecation Warning

### ISSUE THREAD

**Issue by yogiben** [magiclabs/magic-js#571]
### ✅ Prerequisites

- [x ] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Can you point me to the correct documentation for this upgrade? The API is not the same.

<img width="339" alt="image" src="https://github.com/magiclabs/magic-js/assets/1703155/dc42f1c0-a8bc-40a0-b8a5-65be4726ea13">

**Comment by ayv8er** [comment]
@yogiben please consider this a pre-notice. We will ensure all developers have ample time to prepare for this once we have external docs on how to transition.
