### ISSUE TITLE
Infinite loading screen executing showUI

### ISSUE THREAD

**Issue by nicomanzato** [magiclabs/magic-js#588]
### ✅ Prerequisites

- [X] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [X] Are you running the latest SDK version?
- [X] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Hello! I'm building a wallet using expo and want to allow users to access the topup funcionality but when executing the `showUI` method I get an infinite loading screen without an error. Below is a repo that reproduces my issue.

### 🧩 Steps to Reproduce

1. Sign in with Google using the login button.
2. Click on `Show UI` button

### 🤔 Expected behavior

Render the wallet widget (https://magic.link/docs/connect/features/wallet-widget) to access the fiat on ramp.

### 😮 Actual behavior

There is a infinite loading screen never finishes loading.

### 💻 Code Sample

https://github.com/nicomanzato/test-magic-link

### Video

https://github.com/magiclabs/magic-js/assets/11561180/c4219968-9b9d-4fd4-94c6-ea422c046f68

**Comment by am-hernandez** [comment]
Hi @nicomanzato ,

Because you are using Solana this method will not work because the Wallet Widget only supports Ethereum, Optimism, and Polygon. You should have seen errors logged to console indicating the incompatibility. 

Would you let me know if you are seeing these errors?

**Comment by nicomanzato** [comment]
I've not seen those errors so far, are they supposed to appear when executing `showUI`?

**Comment by am-hernandez** [comment]
@nicomanzato the error should throw for the `showUI` method and the `connectWithUI` method. I am going to repro this in a demo app soon and report back with expected behavior.

**Comment by nicomanzato** [comment]
Yup, never seen that error in either of those methods. Either way it's not going to work for a solana wallet so I've got my answer. I'll close this issue.

Thank you for your quick response!
