### ISSUE TITLE
ReferenceError: window is not defined: NextJS 13.4 App Router

### ISSUE THREAD

**Issue by E0han** [magiclabs/magic-js#609]
I have met an error from initialising an instance of Magic from "magic-sdk" for using in NextJS v13.4 App Router:

```bash
- error node_modules/@magic-sdk/provider/dist/es/index.mjs (5:19770) @ new ne
- error ReferenceError: window is not defined
    at eval (./src/_libs/magicCLI.js:8:15)
    at (ssr)/./src/_libs/magicCLI.js
    at __webpack_require__ 
    at eval (./src/_context/Web3Context.js:11:72)
    at (ssr)/./src/_context/Web3Context.js 
    at __webpack_require__ 
    at eval (./src/_context/UserContext.js:10:70)
    at (ssr)/./src/_context/UserContext.js 
    at __webpack_require__ 
    at eval (./src/app/[locale]/provider.js:7:78)
    at (ssr)/./src/app/[locale]/provider.js
    at __webpack_require__ 
```

Also got the warning post here:

#559 

It appears on the server side, and I can see it might caused by the ssr feature from nextjs and the way `@magic-sdk/provider` working, but even I defined  my provider with `'use client'` directive but it still rendering this instance within server side.

My approach:

```js
'use client'
//MagicCLI.js
import { Magic} from "magic-sdk"

export const magic = new Magic(
    process.env.NEXT_PUBLIC_MAGICLINK_API,{
        network: "goerli"
    }
)
```

`Web3Provider.js` and `UserProvider` are followed by [MagicLink React Example](https://magic.link/docs/connect/getting-started/react-tutorial) with using `'use client'` directive

And use the magic instance for Web3Provider and UserProvider in Provider:
```js
'use client'

import { UserProvider } from '@/_context/UserContext'
import { Web3Provider } from '@/_context/Web3Context'

import {NextUIProvider} from '@nextui-org/react'
import { ThemeProvider as NextThemeProvider } from 'next-themes'

export function Providers({children}) {
  return (
    <NextUIProvider>
      <NextThemeProvider attribute='class' defaultTheme='dark'>
        <Web3Provider>
          <UserProvider>
            {children}
          </UserProvider>
        </Web3Provider>
      </NextThemeProvider>
    </NextUIProvider>
  )
}
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | ^19.2.0
| Browser          | Google Chrome
| `next`           | 13.4.13
| `react`           | 18.2.0
| Operating System | MacOS

**Comment by am-hernandez** [comment]
Hello @E0han , 

Thank you for posting this issue. With Next JS your instantiation is likely happening server-side where `window` is not defined. You can make sure Magic is being instantiated when the window object is present with the following snippet:

```js
const createMagic = () => {
  return typeof window != 'undefined' && new Magic('YOUR_API_KEY');
};

export const magic = createMagic();
```

**Comment by mtsdalmolin** [comment]
I'm trying to do that verification but the compiler keeps yelling at me.

Looking up to see if there is anyone else having this problem, I found this issue (https://github.com/vercel/next.js/issues/36514) and posted my doubt there.
What am I doing wrong? 🤔 @am-hernandez
