### ISSUE TITLE
Magic RPC Error: [-32603] Internal error: User denied account access.

### ISSUE THREAD

**Issue by pondskai** [magiclabs/magic-js#628]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

i try to use magic.wallet.showUI() in my dApp. it works fine when a users connects with email. When connects with metamask, i got an error Magic RPC Error: [-32603] Internal error: User denied account access. 

### 🧩 Steps to Reproduce

1. use magic link with metamask
2. try show magic wallet widget

### 🤔 Expected behavior

the magic wallet widget shows

### 😮 Actual behavior

nothing shows and see an error Magic RPC Error: [-32603] Internal error: User denied account access. 

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |   ^20.0.1 |
| Browser          | chrome |
| `yarn`           | 
| Operating System | mac |

**Comment by am-hernandez** [comment]
Hello @pondskai ,

You can not show the MetaMask UI by calling `showUI()`, it will only work for the Magic wallet connections. For MetaMask, the user may click the MetaMask icon in their browser to open the view of that wallet. Please refer to our doc on [showUI](https://magic.link/docs/universal/wallet-api-reference/javascript-client-sdk#showui)


> ![showUI](https://github.com/magiclabs/magic-js/assets/86538622/ab593d16-ac9b-42a1-8e72-00146df41834)
> [source](https://magic.link/docs/universal/wallet-api-reference/javascript-client-sdk#showui)
