### ISSUE TITLE
Support Base blockchain

### ISSUE THREAD

**Issue by 0xtrou** [magiclabs/magic-js#645]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request

Currently Base blockchain is becoming more popular, should we consider supporting Base blockchain in the UI Widget?

**Comment by am-hernandez** [comment]
Hello @0xtrou ,

Thank you for the feature request. Base is currently supported for Dedicated wallets using the following public RPC URLs: 
- https://mainnet.base.org/
- https://goerli.base.org/

You should add the RPC URL you are using to your app's settings in the Magic dashboard under your app's Content Security Policy. This way you can assure that these RPC URLs will work for your app as we continue to make changes to our own Content Security Policy and remove these public RPC URLs.

> <img width="1043" alt="dashboard_csp" src="https://github.com/magiclabs/magic-js/assets/86538622/a5a77ef5-9559-44a3-b4ce-039f56f98295">
> add RPC URLs to your Dedicated app's Content Security Policy

---

**Base is not supported for Universal wallets and the Widget UI currently, even if you have added the RPC URL to your Dedicated app's content security policy.**

We will take this feature request of supporting Base in the Widget UI under consideration and follow up in this Issue thread if we decide to provide this support.

Thank you!
