### ISSUE TITLE
TypeScript cannot access types of @magic-ext/* packages when moduleResolution = "node16" in tsconfig.json

### ISSUE THREAD

**Issue by rjwebb** [magiclabs/magic-js#669]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I'm currently exploring how my team can integrate Magic into an existing web app which was using `Node16` module resolution. I found that if I tried to import any `@magic-ext/*` packages then I would get an error with some variation on:

```
src/main.ts:15:18 - error TS7016: Could not find a declaration file for module '@magic-ext/oidc'. '/Users/bob/code/work/canvas/magic-module-import-reproduce/node_modules/.pnpm/@magic-ext+oidc@4.3.0/node_modules/@magic-ext/oidc/dist/es/index.mjs' implicitly has an 'any' type.
  There are types at '/Users/bob/code/work/canvas/magic-module-import-reproduce/node_modules/@magic-ext/oidc/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@magic-ext/oidc' library may need to update its package.json or typings.

15 import oidc from "@magic-ext/oidc"
                    ~~~~~~~~~~~~~~~~~
```

replacing "@magic-ext/oidc" with the particular module being imported.

I think this is a pretty big deal - if we want Magic to be supported by modern web apps then we should be supporting more recent module resolution methods. I'm happy to make a PR for this.

### 🧩 Steps to Reproduce

1. Create a Typescript project that uses `Node16` or `NodeNext` for the module and moduleResolution settings in tsconfig.json
2. Try to import something from `@magic-ext/*`

You should see an error in tsc looking something like the quoted text in the description of this issue.

### 💻 Code Sample

I've created a repo that provides a minimal example that triggers this error.

https://github.com/rjwebb/magic-module-import-reproduce

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | N/A
| Browser          | N/A
| `yarn`           | I used pnpm 8.10.0
| Operating System | Mac OS

### Solution?

I think I know how to solve this - we just need to add a `types` value to the `exports` object in `package.json` for the affected packages, i.e. copy the fix in https://github.com/magiclabs/magic-js/pull/626

**Comment by Ariflo** [comment]
:rocket: Issue was released in [`@magic-ext/algorand@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/algorand%4016.3.1), [`@magic-ext/auth@4.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/auth%404.3.1), [`@magic-ext/avalanche@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/avalanche%4016.3.1), [`@magic-ext/bitcoin@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/bitcoin%4016.3.1), [`@magic-ext/conflux@14.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/conflux%4014.3.1), [`@magic-ext/cosmos@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/cosmos%4016.3.1), [`@magic-ext/ed25519@12.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/ed25519%4012.3.1), [`@magic-ext/flow@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/flow%4016.3.1), [`@magic-ext/gdkms@4.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/gdkms%404.3.1), [`@magic-ext/harmony@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/harmony%4016.3.1), [`@magic-ext/hedera@1.0.3`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/hedera%401.0.3), [`@magic-ext/icon@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/icon%4016.3.1), [`@magic-ext/near@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/near%4016.3.1), [`@magic-ext/oauth@15.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/oauth%4015.3.1), [`@magic-ext/oidc@4.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/oidc%404.3.1), [`@magic-ext/polkadot@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/polkadot%4016.3.1), [`@magic-ext/react-native-bare-oauth@18.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-bare-oauth%4018.0.1), [`@magic-ext/react-native-expo-oauth@18.0.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/react-native-expo-oauth%4018.0.1), [`@magic-ext/taquito@13.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/taquito%4013.3.1), [`@magic-ext/terra@13.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/terra%4013.3.1), [`@magic-ext/tezos@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/tezos%4016.3.1), [`@magic-ext/webauthn@15.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/webauthn%4015.3.1), [`@magic-ext/zilliqa@16.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-ext/zilliqa%4016.3.1), [`@magic-sdk/pnp@15.3.1`](https://github.com/magiclabs/magic-js/releases/tag/%40magic-sdk/pnp%4015.3.1) :rocket:
