### ISSUE TITLE
MagicSDK stopped working since yesterday: MODAL_NOT_READY or network timeout

### ISSUE THREAD

**Issue by pax-k** [magiclabs/magic-js#672]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When trying to call `const isMagicLoggedIn = await magic.user.isLoggedIn();`, I either get this error: `Magic SDK Error: [MODAL_NOT_READY] Modal is not ready.`, either the await never gets resolved. 

### 🧩 Steps to Reproduce

Install the below documented dependencies and run the code sample.

### 🤔 Expected behavior

I expect no error or timeouts.

### 😮 Actual behavior

I receive MODAL_NOT_READY or the await call never gets resolved.

### 💻 Code Sample

```
import { Magic, useInternetConnection } from '@magic-sdk/react-native-expo';
import { useEffect, useState } from 'react';

export const MagicAuth = ({ children, apiKey }) => {
  const [magic, setMagic] = useState<Magic | null>(null);
  const connected = useInternetConnection();

  const checkAuth = async () => {
    if (magic === null) return;
    const isMagicLoggedIn = await magic.user.isLoggedIn(); // this either triggers MODAL_NOT_READY error, either the await never resolves
    console.log('isMagicLoggedIn', isMagicLoggedIn);
  };

  useEffect(() => {
    const magic = new Magic(apiKey);
    setMagic(magic);
  }, []);

  useEffect(() => {
    if (magic && connected) checkAuth();
  }, [magic, connected]);


  return (
    <>
      {magic !== null && connected ? <magic.Relayer /> : null}
    </>
  );
};
```

### 🌎 Environment

- yarn
```
"react-native": "0.72.6",
"expo": "^49.0.11",
"@magic-sdk/react-native-expo": "22.3.0",
"@react-native-community/netinfo": "11.1.0",
```

**Comment by VirenMohindra** [comment]
Facing the same issue. Our fix is to retry `magic.user.isLoggedIn()`. It shows up the second time round.

**Comment by VirenMohindra** [comment]
Facing the same issue. Our fix is to retry `magic.user.isLoggedIn()`. It shows up the second time round.

```tsx
  const checkIfLoggedIn = async () => {
    try {
      const isLoggedIn = await magic.user.isLoggedIn()
      if (!isLoggedIn) await logout()
    } catch (e) {
      console.log('error', e)
    }
  }
  ```
  
  ```
"react-native": "0.72.6",
"expo": "~49.0.13",
"@magic-sdk/react-native-expo": "^22.0.0",
```

we did not install `netinfo`
