### ISSUE TITLE
magic-sdk signIn / signOut flow not working.

### ISSUE THREAD

**Issue by paro-paro** [magiclabs/magic-js#740]
Hi! 

Something went really wrong with the magic-sdk for web. 

After a successfull `magic.user.logout()`, a following log in attempt with `magic.wallet.connectWithUI()` will not trigger the modal as expected. 

Instead, it will return the user eoa/account but the user wont be actually authenticated so any following call to any sdk method will throw a `Magic RPC Error: [-32603] User denied account access.` , breaking current web applications sign in flow. 

You have to manually refresh the page in order to make it work. I believe this is a hight priority issue.

I just created a quick repro in stackblitz using the latest version of the package and it is indeed failing as explained.

[reproduction](https://stackblitz.com/edit/github-kddxnn)

**Comment by Dizigen** [comment]
@paro-paro thank you for flagging this! we have isolated the issue and will put out a fix on monday.

**Comment by paro-paro** [comment]
Awesome! Thanks for the quick response!

**Comment by Dizigen** [comment]
@paro-paro this should be fixed now

**Comment by paro-paro** [comment]
@Dizigen I can confirm that everything went back to normal. Thanks for the fix.
