### ISSUE TITLE
White Screen on iOS blocks whole app.

### ISSUE THREAD

**Issue by johanneskares** [magiclabs/magic-js#787]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

This PR breaks iOS Safari: https://github.com/magiclabs/magic-js/pull/772

It causes a white screen overlay over the whole app on iOS, when initialzing the magic SDK. The PR should be reverted.

### 🧩 Steps to Reproduce

1. Go here: https://talentir-dwna2lwpb-talentir.vercel.app
2. White screen after a couple of seconds
3. I downgraded to 28.3.0, it's working, if I upgrade to 28.3.1 I get the white screen, again

### 🤔 Expected behavior

No white screen

### 😮 Actual behavior

White screen

### 💻 Code Sample

I created a custom wagmi connector. All I do is initialize it:

```ts
new Magic("pk_live_xxxxxx", {
    network: {
        rpcUrl,
         chainId: chain.id,
    },
})
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | > 28.3.1
| Browser          | Safari iOS
| `yarn`           | bun
| Operating System | iOS

**Comment by romin-halltari** [comment]
Hey @johanneskares thanks for flagging this. Can you install `"magic-sdk": "28.5.1-canary.788.10672694974.0"` and check if the issue still persists? I'll release a new version afterwards.

**Comment by johanneskares** [comment]
Yes, confirmed, this release fixes it.
