### ISSUE TITLE
Circle CI tag in readme is broken

### ISSUE THREAD

**Issue by Ethella** [magiclabs/magic-js#99]
Context
--- 

![image](https://user-images.githubusercontent.com/33166884/83301094-de58d800-a1ad-11ea-9251-5058f079b20f.png)
https://circleci.com/gh/MagicHQ/magic-js

Circle CI is broken

**Comment by smithki** [comment]
We recently renamed the GitHub organization from `MagicHQ` to `MagicLabs`, which explains this. I'll make sure it's resolved before the next release 😃
